name: Suggest a Feature or Change
description: Have a new Idea, then suggest a Feature here.
title: "[Suggestion] "
labels: ["suggestion"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new Feature for BetterNether. We appreciate your time!
  - type: textarea
    id: describe
    attributes:
      label: Description
      description: Tell us your idea
      placeholder: 
      value: 
    validations:
      required: true