package paulevs.betternether.registers;

import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.block.MaterialColor;
import net.minecraft.block.PressurePlateBlock.ActivationRule;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;
import paulevs.betternether.BetterNether;
import paulevs.betternether.blocks.BNBarStool;
import paulevs.betternether.blocks.BNBoneBlock;
import paulevs.betternether.blocks.BNButton;
import paulevs.betternether.blocks.BNDoor;
import paulevs.betternether.blocks.BNFence;
import paulevs.betternether.blocks.BNGate;
import paulevs.betternether.blocks.BNGlass;
import paulevs.betternether.blocks.BNLadder;
import paulevs.betternether.blocks.BNLogStripable;
import paulevs.betternether.blocks.BNNetherBrick;
import paulevs.betternether.blocks.BNNormalChair;
import paulevs.betternether.blocks.BNPane;
import paulevs.betternether.blocks.BNPillar;
import paulevs.betternether.blocks.BNPlanks;
import paulevs.betternether.blocks.BNPlate;
import paulevs.betternether.blocks.BNSlab;
import paulevs.betternether.blocks.BNStairs;
import paulevs.betternether.blocks.BNTaburet;
import paulevs.betternether.blocks.BNTrapdoor;
import paulevs.betternether.blocks.BNWall;
import paulevs.betternether.blocks.BlockAgave;
import paulevs.betternether.blocks.BlockBarrelCactus;
import paulevs.betternether.blocks.BlockBlackApple;
import paulevs.betternether.blocks.BlockBlackAppleSeed;
import paulevs.betternether.blocks.BlockBlackBush;
import paulevs.betternether.blocks.BlockBlackVine;
import paulevs.betternether.blocks.BlockBoneMushroom;
import paulevs.betternether.blocks.BlockBrownLargeMushroom;
import paulevs.betternether.blocks.BlockChestOfDrawers;
import paulevs.betternether.blocks.BlockCincinnasitPillar;
import paulevs.betternether.blocks.BlockCincinnasite;
import paulevs.betternether.blocks.BlockCincinnasiteFireBowl;
import paulevs.betternether.blocks.BlockCincinnasiteFrame;
import paulevs.betternether.blocks.BlockCincinnasiteLantern;
import paulevs.betternether.blocks.BlockCincinnasiteOre;
import paulevs.betternether.blocks.BlockCincinnasitePedestal;
import paulevs.betternether.blocks.BlockCincinnasitePot;
import paulevs.betternether.blocks.BlockEggPlant;
import paulevs.betternether.blocks.BlockEyeSeed;
import paulevs.betternether.blocks.BlockEyeVine;
import paulevs.betternether.blocks.BlockEyeball;
import paulevs.betternether.blocks.BlockEyeballSmall;
import paulevs.betternether.blocks.BlockFarmland;
import paulevs.betternether.blocks.BlockGeyser;
import paulevs.betternether.blocks.BlockGoldenVine;
import paulevs.betternether.blocks.BlockGrayMold;
import paulevs.betternether.blocks.BlockInkBush;
import paulevs.betternether.blocks.BlockInkBushSeed;
import paulevs.betternether.blocks.BlockLucisMushroom;
import paulevs.betternether.blocks.BlockLucisSpore;
import paulevs.betternether.blocks.BlockMagmaFlower;
import paulevs.betternether.blocks.BlockMushroomFir;
import paulevs.betternether.blocks.BlockMushroomFirSapling;
import paulevs.betternether.blocks.BlockNetherCactus;
import paulevs.betternether.blocks.BlockNetherGrass;
import paulevs.betternether.blocks.BlockNetherMycelium;
import paulevs.betternether.blocks.BlockNetherReed;
import paulevs.betternether.blocks.BlockNetherrackFurnace;
import paulevs.betternether.blocks.BlockNetherrackMoss;
import paulevs.betternether.blocks.BlockOrangeMushroom;
import paulevs.betternether.blocks.BlockPlantWall;
import paulevs.betternether.blocks.BlockPottedPlant;
import paulevs.betternether.blocks.BlockRedLargeMushroom;
import paulevs.betternether.blocks.BlockRedMold;
import paulevs.betternether.blocks.BlockReedsBlock;
import paulevs.betternether.blocks.BlockSmallLantern;
import paulevs.betternether.blocks.BlockSmoker;
import paulevs.betternether.blocks.BlockSoulGrass;
import paulevs.betternether.blocks.BlockSoulLily;
import paulevs.betternether.blocks.BlockSoulLilySapling;
import paulevs.betternether.blocks.BlockSoulVein;
import paulevs.betternether.blocks.BlockStalagnate;
import paulevs.betternether.blocks.BlockStalagnateBowl;
import paulevs.betternether.blocks.BlockStalagnateSeed;
import paulevs.betternether.blocks.BlockStalagnateStem;
import paulevs.betternether.blocks.BlockStatueRespawner;
import paulevs.betternether.blocks.BlockVeinedSand;
import paulevs.betternether.blocks.BlockWartRoots;
import paulevs.betternether.blocks.BlockWartSeed;
import paulevs.betternether.blocks.BlockWillowBranch;
import paulevs.betternether.blocks.BlockWillowLeaves;
import paulevs.betternether.blocks.BlockWillowSapling;
import paulevs.betternether.blocks.BlockWillowTrunk;
import paulevs.betternether.blocks.CincinnasiteForge;
import paulevs.betternether.blocks.BlockGiantMold;
import paulevs.betternether.blocks.BlockGiantMoldSapling;
import paulevs.betternether.config.Config;
import paulevs.betternether.tab.CreativeTab;

public class BlocksRegister
{
	public static final Block EYEBALL = new BlockEyeball();
	public static final Block EYEBALL_SMALL = new BlockEyeballSmall();
	public static final Block EYE_VINE = new BlockEyeVine();
	public static final Block EYE_SEED = new BlockEyeSeed();
	public static final Block NETHERRACK_MOSS = new BlockNetherrackMoss();
	public static final Block NETHER_GRASS = new BlockNetherGrass();
	public static final Block NETHER_REED = new BlockNetherReed();
	public static final Block STALAGNATE_STEM = new BlockStalagnateStem();
	public static final Block STALAGNATE = new BlockStalagnate();
	public static final Block STALAGNATE_SEED = new BlockStalagnateSeed();
	public static final Block STRIPED_LOG_STALAGNATE = new BNPillar(MaterialColor.LIME_TERRACOTTA);
	public static final Block STRIPED_BARK_STALAGNATE = new BNPillar(MaterialColor.LIME_TERRACOTTA);
	public static final Block STALAGNATE_LOG = new BNLogStripable(MaterialColor.LIME_TERRACOTTA, STRIPED_LOG_STALAGNATE);
	public static final Block STALAGNATE_BARK = new BNLogStripable(MaterialColor.LIME_TERRACOTTA, STRIPED_BARK_STALAGNATE);
	public static final Block STALAGNATE_PLANKS = new BNPlanks(MaterialColor.LIME_TERRACOTTA);
	public static final Block STALAGNATE_PLANKS_STAIRS = new BNStairs(STALAGNATE_PLANKS);
	public static final Block STALAGNATE_PLANKS_SLAB = new BNSlab(STALAGNATE_PLANKS);
	public static final Block STALAGNATE_PLANKS_FENCE = new BNFence(STALAGNATE_PLANKS);
	public static final Block STALAGNATE_PLANKS_GATE = new BNGate(STALAGNATE_PLANKS);
	public static final Block STALAGNATE_PLANKS_BUTTON = new BNButton(STALAGNATE_PLANKS);
	public static final Block STALAGNATE_PLANKS_PLATE = new BNPlate(ActivationRule.EVERYTHING, STALAGNATE_PLANKS);
	public static final Block STALAGNATE_PLANKS_TRAPDOOR = new BNTrapdoor(STALAGNATE_PLANKS);
	public static final Block STALAGNATE_PLANKS_DOOR = new BNDoor(STALAGNATE_PLANKS);
	public static final Block REEDS_BLOCK = new BlockReedsBlock();
	public static final Block REEDS_STAIRS = new BNStairs(REEDS_BLOCK);
	public static final Block REEDS_SLAB = new BNSlab(REEDS_BLOCK);
	public static final Block REEDS_FENCE = new BNFence(REEDS_BLOCK);
	public static final Block REEDS_GATE = new BNGate(REEDS_BLOCK);
	public static final Block REEDS_BUTTON = new BNButton(REEDS_BLOCK);
	public static final Block REEDS_PLATE = new BNPlate(ActivationRule.EVERYTHING, REEDS_BLOCK);
	public static final Block REEDS_TRAPDOOR = new BNTrapdoor(REEDS_BLOCK);
	public static final Block REEDS_DOOR = new BNDoor(REEDS_BLOCK);
	public static final Block LUCIS_MUSHROOM = new BlockLucisMushroom();
	public static final Block LUCIS_SPORE = new BlockLucisSpore();
	public static final Block NETHER_CACTUS = new BlockNetherCactus();
	public static final Block WART_SEED = new BlockWartSeed();
	public static final Block BARREL_CACTUS = new BlockBarrelCactus();
	public static final Block AGAVE = new BlockAgave();
	public static final Block BLACK_BUSH = new BlockBlackBush();
	public static final Block INK_BUSH = new BlockInkBush();
	public static final Block INK_BUSH_SEED = new BlockInkBushSeed();
	public static final Block SMOKER = new BlockSmoker();
	public static final Block EGG_PLANT = new BlockEggPlant();
	public static final Block BLACK_APPLE = new BlockBlackApple();
	public static final Block BLACK_APPLE_SEED = new BlockBlackAppleSeed();
	public static final Block MAGMA_FLOWER = new BlockMagmaFlower();
	public static final Block NETHER_MYCELIUM = new BlockNetherMycelium();
	public static final Block RED_LARGE_MUSHROOM = new BlockRedLargeMushroom();
	public static final Block BROWN_LARGE_MUSHROOM = new BlockBrownLargeMushroom();
	public static final Block ORANGE_MUSHROOM = new BlockOrangeMushroom();
	public static final Block RED_MOLD = new BlockRedMold();
	public static final Block GRAY_MOLD = new BlockGrayMold();
	public static final Block CINCINNASITE_ORE = new BlockCincinnasiteOre();
	public static final Block CINCINNASITE = new BlockCincinnasite();
	public static final Block CINCINNASITE_FORGED = new BlockCincinnasite();
	public static final Block CINCINNASITE_PILLAR = new BlockCincinnasitPillar();
	public static final Block CINCINNASITE_BRICKS = new BlockCincinnasite();
	public static final Block CINCINNASITE_BRICK_PLATE = new BlockCincinnasite();
	public static final Block CINCINNASITE_STAIRS = new BNStairs(CINCINNASITE);
	public static final Block CINCINNASITE_SLAB = new BNSlab(CINCINNASITE);
	public static final Block CINCINNASITE_BUTTON = new BNButton(CINCINNASITE);
	public static final Block CINCINNASITE_PLATE = new BNPlate(ActivationRule.MOBS, CINCINNASITE);
	public static final Block CINCINNASITE_LANTERN = new BlockCincinnasiteLantern();
	public static final Block CINCINNASITE_TILE_LARGE = new BlockCincinnasite();
	public static final Block CINCINNASITE_TILE_SMALL = new BlockCincinnasite();
	public static final Block CINCINNASITE_CARVED = new BlockCincinnasite();
	public static final Block NETHER_BRICK_TILE_LARGE = new BNNetherBrick();
	public static final Block NETHER_BRICK_TILE_SMALL = new BNNetherBrick();
	public static final Block CINCINNASITE_WALL = new BNWall(CINCINNASITE);
	public static final Block BONE = new BNBoneBlock();
	public static final Block BONE_STAIRS = new BNStairs(BONE);
	public static final Block BONE_SLAB = new BNSlab(BONE);
	public static final Block BONE_BUTTON = new BNButton(BONE);
	public static final Block BONE_PLATE = new BNPlate(ActivationRule.EVERYTHING, BONE);
	public static final Block CINCINNASITE_FIRE_BOWL = new BlockCincinnasiteFireBowl();
	public static final Block BONE_WALL = new BNWall(BONE);
	public static final Block NETHER_BRICK_WALL = new BNWall(Blocks.NETHER_BRICKS);
	public static final Block NETHER_BRICK_TILE_SLAB = new BNSlab(NETHER_BRICK_TILE_SMALL);
	public static final Block NETHER_BRICK_TILE_STAIRS = new BNStairs(NETHER_BRICK_TILE_SMALL);
	public static final Block BONE_MUSHROOM = new BlockBoneMushroom();
	public static final Block REEDS_LADDER = new BNLadder(REEDS_BLOCK);
	public static final Block CINCINNASITE_BRICKS_PILLAR = new BNPillar(CINCINNASITE);
	public static final Block BONE_TILE = new BNBoneBlock();
	public static final Block CINCINNASITE_PEDESTAL = new BlockCincinnasitePedestal();
	public static final Block PIG_STATUE_RESPAWNER = new BlockStatueRespawner();
	public static final Block CINCINNASITE_POT = new BlockCincinnasitePot();
	public static final Block POTTED_PLANT = new BlockPottedPlant();
	public static final Block CINCINNASITE_FRAME = new BlockCincinnasiteFrame();
	public static final Block QUARTZ_GLASS = new BNGlass(Blocks.GLASS);
	public static final Block QUARTZ_GLASS_FRAMED = new BNGlass(CINCINNASITE);
	public static final Block QUARTZ_WHITE_GLASS = new BNGlass(QUARTZ_GLASS);
	public static final Block QUARTZ_ORANGE_GLASS = new BNGlass(QUARTZ_GLASS);
	public static final Block QUARTZ_MAGENTA_GLASS = new BNGlass(QUARTZ_GLASS);
	public static final Block QUARTZ_LIGHT_BLUE_GLASS = new BNGlass(QUARTZ_GLASS);
	public static final Block QUARTZ_YELLOW_GLASS = new BNGlass(QUARTZ_GLASS);
	public static final Block QUARTZ_LIME_GLASS = new BNGlass(QUARTZ_GLASS);
	public static final Block QUARTZ_PINK_GLASS = new BNGlass(QUARTZ_GLASS);
	public static final Block QUARTZ_GRAY_GLASS = new BNGlass(QUARTZ_GLASS);
	public static final Block QUARTZ_LIGHT_GRAY_GLASS = new BNGlass(QUARTZ_GLASS);
	public static final Block QUARTZ_CYAN_GLASS = new BNGlass(QUARTZ_GLASS);
	public static final Block QUARTZ_PURPLE_GLASS = new BNGlass(QUARTZ_GLASS);
	public static final Block QUARTZ_BLUE_GLASS = new BNGlass(QUARTZ_GLASS);
	public static final Block QUARTZ_BROWN_GLASS = new BNGlass(QUARTZ_GLASS);
	public static final Block QUARTZ_GREEN_GLASS = new BNGlass(QUARTZ_GLASS);
	public static final Block QUARTZ_RED_GLASS = new BNGlass(QUARTZ_GLASS);
	public static final Block QUARTZ_BLACK_GLASS = new BNGlass(QUARTZ_GLASS);
	public static final Block CINCINNASITE_BARS = new BNPane(CINCINNASITE, true);
	public static final Block QUARTZ_GLASS_PANE = new BNPane(QUARTZ_GLASS, true);
	public static final Block QUARTZ_GLASS_FRAMED_PANE = new BNPane(CINCINNASITE, true);
	public static final Block CINCINNASITE_FORGE = new CincinnasiteForge();
	public static final Block NETHERRACK_FURNACE = new BlockNetherrackFurnace();
	public static final Block BONE_REED_DOOR = new BNDoor(BONE);
	public static final Block BONE_CINCINNASITE_DOOR = new BNDoor(BONE);
	public static final Block QUARTZ_GLASS_FRAMED_WHITE = new BNGlass(QUARTZ_GLASS_FRAMED);
	public static final Block QUARTZ_GLASS_FRAMED_ORANGE = new BNGlass(QUARTZ_GLASS_FRAMED);
	public static final Block QUARTZ_GLASS_FRAMED_MAGENTA = new BNGlass(QUARTZ_GLASS_FRAMED);
	public static final Block QUARTZ_GLASS_FRAMED_LIGHT_BLUE = new BNGlass(QUARTZ_GLASS_FRAMED);
	public static final Block QUARTZ_GLASS_FRAMED_YELLOW = new BNGlass(QUARTZ_GLASS_FRAMED);
	public static final Block QUARTZ_GLASS_FRAMED_LIME = new BNGlass(QUARTZ_GLASS_FRAMED);
	public static final Block QUARTZ_GLASS_FRAMED_PINK = new BNGlass(QUARTZ_GLASS_FRAMED);
	public static final Block QUARTZ_GLASS_FRAMED_GRAY = new BNGlass(QUARTZ_GLASS_FRAMED);
	public static final Block QUARTZ_GLASS_FRAMED_LIGHT_GRAY = new BNGlass(QUARTZ_GLASS_FRAMED);
	public static final Block QUARTZ_GLASS_FRAMED_CYAN = new BNGlass(QUARTZ_GLASS_FRAMED);
	public static final Block QUARTZ_GLASS_FRAMED_PURPLE = new BNGlass(QUARTZ_GLASS_FRAMED);
	public static final Block QUARTZ_GLASS_FRAMED_BLUE = new BNGlass(QUARTZ_GLASS_FRAMED);
	public static final Block QUARTZ_GLASS_FRAMED_BROWN = new BNGlass(QUARTZ_GLASS_FRAMED);
	public static final Block QUARTZ_GLASS_FRAMED_GREEN = new BNGlass(QUARTZ_GLASS_FRAMED);
	public static final Block QUARTZ_GLASS_FRAMED_RED = new BNGlass(QUARTZ_GLASS_FRAMED);
	public static final Block QUARTZ_GLASS_FRAMED_BLACK = new BNGlass(QUARTZ_GLASS_FRAMED);
	public static final Block STALAGNATE_BOWL = new BlockStalagnateBowl();
	public static final Block CHEST_OF_DRAWERS = new BlockChestOfDrawers();
	public static final Block FARMLAND = new BlockFarmland();
	public static final Block WILLOW_BRANCH = new BlockWillowBranch();
	public static final Block WILLOW_LEAVES = new BlockWillowLeaves();
	public static final Block WILLOW_TRUNK = new BlockWillowTrunk();
	public static final Block STRIPED_LOG_WILLOW = new BNPillar(MaterialColor.PINK);
	public static final Block STRIPED_BARK_WILLOW = new BNPillar(MaterialColor.PINK);
	public static final Block WILLOW_LOG = new BNLogStripable(MaterialColor.RED_TERRACOTTA, STRIPED_LOG_WILLOW);
	public static final Block WILLOW_BARK = new BNLogStripable(MaterialColor.RED_TERRACOTTA, STRIPED_BARK_WILLOW);
	public static final Block WILLOW_SAPLING = new BlockWillowSapling();
	public static final Block SWAMP_GRASS = new BlockNetherGrass();
	public static final Block WILLOW_PLANKS = new BNPlanks(MaterialColor.RED_TERRACOTTA);
	public static final Block WILLOW_STAIRS = new BNStairs(WILLOW_PLANKS);
	public static final Block WILLOW_SLAB = new BNSlab(WILLOW_PLANKS);
	public static final Block WILLOW_FENCE = new BNFence(WILLOW_PLANKS);
	public static final Block WILLOW_GATE = new BNGate(WILLOW_PLANKS);
	public static final Block WILLOW_BUTTON = new BNButton(WILLOW_PLANKS);
	public static final Block WILLOW_PLATE = new BNPlate(ActivationRule.EVERYTHING, WILLOW_PLANKS);
	public static final Block WILLOW_TRAPDOOR = new BNTrapdoor(WILLOW_PLANKS);
	public static final Block WILLOW_DOOR = new BNDoor(WILLOW_PLANKS);
	public static final Block WART_PLANKS = new BNPlanks(MaterialColor.RED);
	public static final Block WART_STAIRS = new BNStairs(WART_PLANKS);
	public static final Block WART_SLAB = new BNSlab(WART_PLANKS);
	public static final Block WART_FENCE = new BNFence(WART_PLANKS);
	public static final Block WART_GATE = new BNGate(WART_PLANKS);
	public static final Block WART_BUTTON = new BNButton(WART_PLANKS);
	public static final Block WART_PLATE = new BNPlate(ActivationRule.EVERYTHING, WART_PLANKS);
	public static final Block WART_TRAPDOOR = new BNTrapdoor(WART_PLANKS);
	public static final Block WART_DOOR = new BNDoor(WART_PLANKS);
	public static final Block BLACK_VINE = new BlockBlackVine();
	public static final Block VEINED_SAND = new BlockVeinedSand();
	public static final Block SOUL_VEIN = new BlockSoulVein();
	public static final Block BLOOMING_VINE = new BlockBlackVine();
	public static final Block GOLDEN_VINE = new BlockGoldenVine();
	public static final Block GEYSER = new BlockGeyser();
	public static final Block MUSHROOM_STEM = new BlockStalagnateStem();
	public static final Block MUSHROOM_PLANKS = new BNPlanks(MaterialColor.LIGHT_GRAY);
	public static final Block MUSHROOM_STAIRS = new BNStairs(MUSHROOM_PLANKS);
	public static final Block MUSHROOM_SLAB = new BNSlab(MUSHROOM_PLANKS);
	public static final Block MUSHROOM_FENCE = new BNFence(MUSHROOM_PLANKS);
	public static final Block MUSHROOM_GATE = new BNGate(MUSHROOM_PLANKS);
	public static final Block MUSHROOM_BUTTON = new BNButton(MUSHROOM_PLANKS);
	public static final Block MUSHROOM_PLATE = new BNPlate(ActivationRule.EVERYTHING, MUSHROOM_PLANKS);
	public static final Block MUSHROOM_TRAPDOOR = new BNTrapdoor(MUSHROOM_STAIRS);
	public static final Block MUSHROOM_DOOR = new BNDoor(MUSHROOM_STAIRS);
	public static final Block CINCINNASITE_LANTERN_SMALL = new BlockSmallLantern();
	public static final Block QUARTZ_GLASS_PANE_WHITE = new BNPane(QUARTZ_GLASS, false);
	public static final Block QUARTZ_GLASS_PANE_ORANGE = new BNPane(QUARTZ_GLASS, false);
	public static final Block QUARTZ_GLASS_PANE_MAGENTA = new BNPane(QUARTZ_GLASS, false);
	public static final Block QUARTZ_GLASS_PANE_LIGHT_BLUE = new BNPane(QUARTZ_GLASS, false);
	public static final Block QUARTZ_GLASS_PANE_YELLOW = new BNPane(QUARTZ_GLASS, false);
	public static final Block QUARTZ_GLASS_PANE_LIME = new BNPane(QUARTZ_GLASS, false);
	public static final Block QUARTZ_GLASS_PANE_PINK = new BNPane(QUARTZ_GLASS, false);
	public static final Block QUARTZ_GLASS_PANE_GRAY = new BNPane(QUARTZ_GLASS, false);
	public static final Block QUARTZ_GLASS_PANE_LIGHT_GRAY = new BNPane(QUARTZ_GLASS, false);
	public static final Block QUARTZ_GLASS_PANE_CYAN = new BNPane(QUARTZ_GLASS, false);
	public static final Block QUARTZ_GLASS_PANE_PURPLE = new BNPane(QUARTZ_GLASS, false);
	public static final Block QUARTZ_GLASS_PANE_BLUE = new BNPane(QUARTZ_GLASS, false);
	public static final Block QUARTZ_GLASS_PANE_BROWN = new BNPane(QUARTZ_GLASS, false);
	public static final Block QUARTZ_GLASS_PANE_GREEN = new BNPane(QUARTZ_GLASS, false);
	public static final Block QUARTZ_GLASS_PANE_RED = new BNPane(QUARTZ_GLASS, false);
	public static final Block QUARTZ_GLASS_PANE_BLACK = new BNPane(QUARTZ_GLASS, false);
	public static final Block QUARTZ_GLASS_FRAMED_PANE_WHITE = new BNPane(QUARTZ_GLASS_FRAMED, true);
	public static final Block QUARTZ_GLASS_FRAMED_PANE_ORANGE = new BNPane(QUARTZ_GLASS_FRAMED, true);
	public static final Block QUARTZ_GLASS_FRAMED_PANE_MAGENTA = new BNPane(QUARTZ_GLASS_FRAMED, true);
	public static final Block QUARTZ_GLASS_FRAMED_PANE_LIGHT_BLUE = new BNPane(QUARTZ_GLASS_FRAMED, true);
	public static final Block QUARTZ_GLASS_FRAMED_PANE_YELLOW = new BNPane(QUARTZ_GLASS_FRAMED, true);
	public static final Block QUARTZ_GLASS_FRAMED_PANE_LIME = new BNPane(QUARTZ_GLASS_FRAMED, true);
	public static final Block QUARTZ_GLASS_FRAMED_PANE_PINK = new BNPane(QUARTZ_GLASS_FRAMED, true);
	public static final Block QUARTZ_GLASS_FRAMED_PANE_GRAY = new BNPane(QUARTZ_GLASS_FRAMED, true);
	public static final Block QUARTZ_GLASS_FRAMED_PANE_LIGHT_GRAY = new BNPane(QUARTZ_GLASS_FRAMED, true);
	public static final Block QUARTZ_GLASS_FRAMED_PANE_CYAN = new BNPane(QUARTZ_GLASS_FRAMED, true);
	public static final Block QUARTZ_GLASS_FRAMED_PANE_PURPLE = new BNPane(QUARTZ_GLASS_FRAMED, true);
	public static final Block QUARTZ_GLASS_FRAMED_PANE_BLUE = new BNPane(QUARTZ_GLASS_FRAMED, true);
	public static final Block QUARTZ_GLASS_FRAMED_PANE_BROWN = new BNPane(QUARTZ_GLASS_FRAMED, true);
	public static final Block QUARTZ_GLASS_FRAMED_PANE_GREEN = new BNPane(QUARTZ_GLASS_FRAMED, true);
	public static final Block QUARTZ_GLASS_FRAMED_PANE_RED = new BNPane(QUARTZ_GLASS_FRAMED, true);
	public static final Block QUARTZ_GLASS_FRAMED_PANE_BLACK = new BNPane(QUARTZ_GLASS_FRAMED, true);
	public static final Block SOUL_LILY = new BlockSoulLily();
	public static final Block SOUL_LILY_SAPLING = new BlockSoulLilySapling();
	public static final Block SOUL_GRASS = new BlockSoulGrass();
	public static final Block STRIPED_LOG_WART = new BNPillar(MaterialColor.RED);
	public static final Block STRIPED_BARK_WART = new BNPillar(MaterialColor.RED);
	public static final Block WART_LOG = new BNLogStripable(Blocks.NETHER_WART_BLOCK, STRIPED_LOG_WART);
	public static final Block WART_BARK = new BNLogStripable(Blocks.NETHER_WART_BLOCK, STRIPED_BARK_WART);
	public static final Block WART_ROOTS = new BlockWartRoots();
	public static final Block WALL_MOSS = new BlockPlantWall(MaterialColor.RED);
	public static final Block WALL_MUSHROOM_BROWN = new BlockPlantWall(MaterialColor.BROWN);
	public static final Block WALL_MUSHROOM_RED = new BlockPlantWall(MaterialColor.RED);
	public static final Block ROOF_TILE_REEDS = new BNPlanks(MaterialColor.BLUE);
	public static final Block ROOF_TILE_REEDS_STAIRS = new BNStairs(ROOF_TILE_REEDS);
	public static final Block ROOF_TILE_REEDS_SLAB = new BNSlab(ROOF_TILE_REEDS);
	public static final Block ROOF_TILE_STALAGNATE = new BNPlanks(MaterialColor.LIME);
	public static final Block ROOF_TILE_STALAGNATE_STAIRS = new BNStairs(ROOF_TILE_STALAGNATE);
	public static final Block ROOF_TILE_STALAGNATE_SLAB = new BNSlab(ROOF_TILE_STALAGNATE);
	public static final Block ROOF_TILE_NETHER_BRICKS = new BNNetherBrick();
	public static final Block ROOF_TILE_NETHER_BRICKS_STAIRS = new BNStairs(ROOF_TILE_NETHER_BRICKS);
	public static final Block ROOF_TILE_NETHER_BRICKS_SLAB = new BNSlab(ROOF_TILE_NETHER_BRICKS);
	public static final Block ROOF_TILE_CINCINNASITE = new BlockCincinnasite();
	public static final Block ROOF_TILE_CINCINNASITE_STAIRS = new BNStairs(ROOF_TILE_NETHER_BRICKS);
	public static final Block ROOF_TILE_CINCINNASITE_SLAB = new BNSlab(ROOF_TILE_NETHER_BRICKS);
	public static final Block ROOF_TILE_WILLOW = new BNPlanks(MaterialColor.RED_TERRACOTTA);
	public static final Block ROOF_TILE_WILLOW_STAIRS = new BNStairs(ROOF_TILE_WILLOW);
	public static final Block ROOF_TILE_WILLOW_SLAB = new BNSlab(ROOF_TILE_WILLOW);
	public static final Block ROOF_TILE_WART = new BNPlanks(MaterialColor.RED_TERRACOTTA);
	public static final Block ROOF_TILE_WART_STAIRS = new BNStairs(ROOF_TILE_WART);
	public static final Block ROOF_TILE_WART_SLAB = new BNSlab(ROOF_TILE_WART);
	public static final Block TABURET_REEDS = new BNTaburet(REEDS_BLOCK);
	public static final Block TABURET_STALAGNATE = new BNTaburet(STALAGNATE_PLANKS);
	public static final Block TABURET_WILLOW = new BNTaburet(WILLOW_PLANKS);
	public static final Block TABURET_WART = new BNTaburet(WART_PLANKS);
	public static final Block TABURET_CINCINNASITE = new BNTaburet(CINCINNASITE_FORGED);
	public static final Block STALAGNATE_LADDER = new BNLadder(STALAGNATE_PLANKS);
	public static final Block WILLOW_LADDER = new BNLadder(WILLOW_PLANKS);
	public static final Block WART_LADDER = new BNLadder(WART_PLANKS);
	public static final Block CHAIR_REEDS = new BNNormalChair(REEDS_BLOCK);
	public static final Block CHAIR_STALAGNATE = new BNNormalChair(STALAGNATE_PLANKS);
	public static final Block CHAIR_WILLOW = new BNNormalChair(WILLOW_PLANKS);
	public static final Block CHAIR_WART = new BNNormalChair(WART_PLANKS);
	public static final Block CHAIR_CINCINNASITE = new BNNormalChair(CINCINNASITE_FORGED);
	public static final Block BAR_STOOL_REEDS = new BNBarStool(REEDS_BLOCK);
	public static final Block BAR_STOOL_STALAGNATE = new BNBarStool(STALAGNATE_PLANKS);
	public static final Block BAR_STOOL_WILLOW = new BNBarStool(WILLOW_PLANKS);
	public static final Block BAR_STOOL_WART = new BNBarStool(WART_PLANKS);
	public static final Block BAR_STOOL_CINCINNASITE = new BNBarStool(CINCINNASITE_FORGED);
	public static final Block GIANT_MOLD = new BlockGiantMold();
	public static final Block GIANT_MOLD_SAPLING = new BlockGiantMoldSapling();
	public static final Block MUSHROOM_FIR = new BlockMushroomFir();
	public static final Block MUSHROOM_FIR_SAPLING = new BlockMushroomFirSapling();
	
	public static void register()
	{
		registerBlock("eyeball", EYEBALL);
		registerBlock("eyeball_small", EYEBALL_SMALL);
		registerBlockNI("eye_vine", EYE_VINE);
		registerBlock("eye_seed", EYE_SEED);
		registerBlock("netherrack_moss", NETHERRACK_MOSS);
		registerBlock("nether_grass", NETHER_GRASS);
		registerBlock("nether_reed", NETHER_REED);
		registerBlock("stalagnate_stem", STALAGNATE_STEM);
		registerBlockNI("stalagnate", STALAGNATE);
		registerBlock("stalagnate_seed", STALAGNATE_SEED);
		registerBlock("stalagnate_log", STALAGNATE_LOG);
		registerBlock("stalagnate_bark", STALAGNATE_BARK);
		registerBlock("stalagnate_planks", STALAGNATE_PLANKS);
		registerBlock("stalagnate_planks_stairs", STALAGNATE_PLANKS_STAIRS);
		registerBlock("stalagnate_planks_slab", STALAGNATE_PLANKS_SLAB);
		registerBlock("stalagnate_planks_fence", STALAGNATE_PLANKS_FENCE);
		registerBlock("stalagnate_planks_gate", STALAGNATE_PLANKS_GATE);
		registerBlock("stalagnate_planks_button", STALAGNATE_PLANKS_BUTTON);
		registerBlock("stalagnate_planks_plate", STALAGNATE_PLANKS_PLATE);
		registerBlock("stalagnate_planks_trapdoor", STALAGNATE_PLANKS_TRAPDOOR);
		registerBlock("stalagnate_planks_door", STALAGNATE_PLANKS_DOOR);
		registerBlock("reeds_block", REEDS_BLOCK);
		registerBlock("reeds_stairs", REEDS_STAIRS);
		registerBlock("reeds_slab", REEDS_SLAB);
		registerBlock("reeds_fence", REEDS_FENCE);
		registerBlock("reeds_gate", REEDS_GATE);
		registerBlock("reeds_button", REEDS_BUTTON);
		registerBlock("reeds_plate", REEDS_PLATE);
		registerBlock("reeds_trapdoor", REEDS_TRAPDOOR);
		registerBlock("reeds_door", REEDS_DOOR);
		registerBlockNI("lucis_mushroom", LUCIS_MUSHROOM);
		registerBlock("lucis_spore", LUCIS_SPORE);
		registerBlock("nether_cactus", NETHER_CACTUS);
		registerBlock("wart_seed", WART_SEED);
		registerBlock("barrel_cactus", BARREL_CACTUS);
		registerBlock("agave", AGAVE);
		registerBlock("black_bush", BLACK_BUSH);
		registerBlockNI("ink_bush", INK_BUSH);
		registerBlock("ink_bush_seed", INK_BUSH_SEED);
		registerBlock("smoker", SMOKER);
		registerBlock("egg_plant", EGG_PLANT);
		registerBlockNI("black_apple", BLACK_APPLE);
		registerBlock("black_apple_seed", BLACK_APPLE_SEED);
		registerBlock("magma_flower", MAGMA_FLOWER);
		registerBlock("nether_mycelium", NETHER_MYCELIUM);
		registerBlockNI("red_large_mushroom", RED_LARGE_MUSHROOM);
		registerBlockNI("brown_large_mushroom", BROWN_LARGE_MUSHROOM);
		registerBlock("orange_mushroom", ORANGE_MUSHROOM);
		registerBlock("red_mold", RED_MOLD);
		registerBlock("gray_mold", GRAY_MOLD);
		registerBlock("cincinnasite_ore", CINCINNASITE_ORE);
		registerBlock("cincinnasite_block", CINCINNASITE);
		registerBlock("cincinnasite_forged", CINCINNASITE_FORGED);
		registerBlock("cincinnasite_pillar", CINCINNASITE_PILLAR);
		registerBlock("cincinnasite_bricks", CINCINNASITE_BRICKS);
		registerBlock("cincinnasite_brick_plate", CINCINNASITE_BRICK_PLATE);
		registerBlock("cincinnasite_stairs", CINCINNASITE_STAIRS);
		registerBlock("cincinnasite_slab", CINCINNASITE_SLAB);
		registerBlock("cincinnasite_button", CINCINNASITE_BUTTON);
		registerBlock("cincinnasite_plate", CINCINNASITE_PLATE);
		registerBlock("cincinnasite_lantern", CINCINNASITE_LANTERN);
		registerBlock("cincinnasite_tile_large", CINCINNASITE_TILE_LARGE);
		registerBlock("cincinnasite_tile_small", CINCINNASITE_TILE_SMALL);
		registerBlock("cincinnasite_carved", CINCINNASITE_CARVED);
		registerBlock("nether_brick_tile_large", NETHER_BRICK_TILE_LARGE);
		registerBlock("nether_brick_tile_small", NETHER_BRICK_TILE_SMALL);
		registerBlock("cincinnasite_wall", CINCINNASITE_WALL);
		registerBlock("bone_block", BONE);
		registerBlock("bone_stairs", BONE_STAIRS);
		registerBlock("bone_slab", BONE_SLAB);
		registerBlock("bone_button", BONE_BUTTON);
		registerBlock("bone_plate", BONE_PLATE);
		registerBlock("cincinnasite_fire_bowl", CINCINNASITE_FIRE_BOWL);
		registerBlock("bone_wall", BONE_WALL);
		registerBlock("nether_brick_wall", NETHER_BRICK_WALL);
		registerBlock("nether_brick_tile_slab", NETHER_BRICK_TILE_SLAB);
		registerBlock("nether_brick_tile_stairs", NETHER_BRICK_TILE_STAIRS);
		registerBlock("bone_mushroom", BONE_MUSHROOM);
		registerBlock("reeds_ladder", REEDS_LADDER);
		registerBlock("cincinnasite_bricks_pillar", CINCINNASITE_BRICKS_PILLAR);
		registerBlock("bone_tile", BONE_TILE);
		registerBlock("cincinnasite_pedestal", CINCINNASITE_PEDESTAL);
		registerBlock("pig_statue_respawner", PIG_STATUE_RESPAWNER);
		registerBlock("cincinnasite_pot", CINCINNASITE_POT);
		registerBlockNI("potted_plant", POTTED_PLANT);
		registerBlock("cincinnasite_frame", CINCINNASITE_FRAME);
		registerBlock("quartz_glass", QUARTZ_GLASS);
		registerBlock("quartz_glass_framed", QUARTZ_GLASS_FRAMED);
		registerBlock("quartz_glass_white", QUARTZ_WHITE_GLASS);
		registerBlock("quartz_glass_orange", QUARTZ_ORANGE_GLASS);
		registerBlock("quartz_glass_magenta", QUARTZ_MAGENTA_GLASS);
		registerBlock("quartz_glass_light_blue", QUARTZ_LIGHT_BLUE_GLASS);
		registerBlock("quartz_glass_yellow", QUARTZ_YELLOW_GLASS);
		registerBlock("quartz_glass_lime", QUARTZ_LIME_GLASS);
		registerBlock("quartz_glass_pink", QUARTZ_PINK_GLASS);
		registerBlock("quartz_glass_gray", QUARTZ_GRAY_GLASS);
		registerBlock("quartz_glass_light_gray", QUARTZ_LIGHT_GRAY_GLASS);
		registerBlock("quartz_glass_cyan", QUARTZ_CYAN_GLASS);
		registerBlock("quartz_glass_purple", QUARTZ_PURPLE_GLASS);
		registerBlock("quartz_glass_blue", QUARTZ_BLUE_GLASS);
		registerBlock("quartz_glass_brown", QUARTZ_BROWN_GLASS);
		registerBlock("quartz_glass_green", QUARTZ_GREEN_GLASS);
		registerBlock("quartz_glass_red", QUARTZ_RED_GLASS);
		registerBlock("quartz_glass_black", QUARTZ_BLACK_GLASS);
		registerBlock("cincinnasite_bars", CINCINNASITE_BARS);
		registerBlock("quartz_glass_pane", QUARTZ_GLASS_PANE);
		registerBlock("quartz_glass_framed_pane", QUARTZ_GLASS_FRAMED_PANE);
		registerBlock("cincinnasite_forge", CINCINNASITE_FORGE);
		registerBlock("netherrack_furnace", NETHERRACK_FURNACE);
		registerBlock("bone_reed_door", BONE_REED_DOOR);
		registerBlock("bone_cincinnasite_door", BONE_CINCINNASITE_DOOR);
		registerBlock("quartz_glass_framed_white", QUARTZ_GLASS_FRAMED_WHITE);
		registerBlock("quartz_glass_framed_orange", QUARTZ_GLASS_FRAMED_ORANGE);
		registerBlock("quartz_glass_framed_magenta", QUARTZ_GLASS_FRAMED_MAGENTA);
		registerBlock("quartz_glass_framed_light_blue", QUARTZ_GLASS_FRAMED_LIGHT_BLUE);
		registerBlock("quartz_glass_framed_yellow", QUARTZ_GLASS_FRAMED_YELLOW);
		registerBlock("quartz_glass_framed_lime", QUARTZ_GLASS_FRAMED_LIME);
		registerBlock("quartz_glass_framed_pink", QUARTZ_GLASS_FRAMED_PINK);
		registerBlock("quartz_glass_framed_gray", QUARTZ_GLASS_FRAMED_GRAY);
		registerBlock("quartz_glass_framed_light_gray", QUARTZ_GLASS_FRAMED_LIGHT_GRAY);
		registerBlock("quartz_glass_framed_cyan", QUARTZ_GLASS_FRAMED_CYAN);
		registerBlock("quartz_glass_framed_purple", QUARTZ_GLASS_FRAMED_PURPLE);
		registerBlock("quartz_glass_framed_blue", QUARTZ_GLASS_FRAMED_BLUE);
		registerBlock("quartz_glass_framed_brown", QUARTZ_GLASS_FRAMED_BROWN);
		registerBlock("quartz_glass_framed_green", QUARTZ_GLASS_FRAMED_GREEN);
		registerBlock("quartz_glass_framed_red", QUARTZ_GLASS_FRAMED_RED);
		registerBlock("quartz_glass_framed_black", QUARTZ_GLASS_FRAMED_BLACK);
		registerBlockNI("stalagnate_bowl", STALAGNATE_BOWL);
		registerBlock("chest_of_drawers", CHEST_OF_DRAWERS);
		registerBlock("farmland", FARMLAND);
		registerBlockNI("willow_branch", WILLOW_BRANCH);
		registerBlockNI("willow_leaves", WILLOW_LEAVES);
		registerBlockNI("willow_trunk", WILLOW_TRUNK);
		registerBlock("willow_log", WILLOW_LOG);
		registerBlock("willow_bark", WILLOW_BARK);
		registerBlock("willow_sapling", WILLOW_SAPLING);
		registerBlock("swamp_grass", SWAMP_GRASS);
		registerBlock("willow_planks", WILLOW_PLANKS);
		registerBlock("willow_stairs", WILLOW_STAIRS);
		registerBlock("willow_slab", WILLOW_SLAB);
		registerBlock("willow_fence", WILLOW_FENCE);
		registerBlock("willow_gate", WILLOW_GATE);
		registerBlock("willow_button", WILLOW_BUTTON);
		registerBlock("willow_plate", WILLOW_PLATE);
		registerBlock("willow_trapdoor", WILLOW_TRAPDOOR);
		registerBlock("willow_door", WILLOW_DOOR);
		registerBlock("wart_planks", WART_PLANKS);
		registerBlock("wart_stairs", WART_STAIRS);
		registerBlock("wart_slab", WART_SLAB);
		registerBlock("wart_fence", WART_FENCE);
		registerBlock("wart_gate", WART_GATE);
		registerBlock("wart_button", WART_BUTTON);
		registerBlock("wart_plate", WART_PLATE);
		registerBlock("wart_trapdoor", WART_TRAPDOOR);
		registerBlock("wart_door", WART_DOOR);
		registerBlock("black_vine", BLACK_VINE);
		registerBlockNI("veined_sand", VEINED_SAND);
		registerBlock("soul_vein", SOUL_VEIN);
		registerBlock("blooming_vine", BLOOMING_VINE);
		registerBlock("golden_vine", GOLDEN_VINE);
		registerBlock("geyser", GEYSER);
		registerBlock("mushroom_stem", MUSHROOM_STEM);
		registerBlock("mushroom_planks", MUSHROOM_PLANKS);
		registerBlock("mushroom_stairs", MUSHROOM_STAIRS);
		registerBlock("mushroom_slab", MUSHROOM_SLAB);
		registerBlock("mushroom_fence", MUSHROOM_FENCE);
		registerBlock("mushroom_gate", MUSHROOM_GATE);
		registerBlock("mushroom_button", MUSHROOM_BUTTON);
		registerBlock("mushroom_plate", MUSHROOM_PLATE);
		registerBlock("mushroom_trapdoor", MUSHROOM_TRAPDOOR);
		registerBlock("mushroom_door", MUSHROOM_DOOR);
		registerBlock("cincinnasite_lantern_small", CINCINNASITE_LANTERN_SMALL);
		registerBlock("quartz_glass_pane_white", QUARTZ_GLASS_PANE_WHITE);
		registerBlock("quartz_glass_pane_orange", QUARTZ_GLASS_PANE_ORANGE);
		registerBlock("quartz_glass_pane_magenta", QUARTZ_GLASS_PANE_MAGENTA);
		registerBlock("quartz_glass_pane_light_blue", QUARTZ_GLASS_PANE_LIGHT_BLUE);
		registerBlock("quartz_glass_pane_yellow", QUARTZ_GLASS_PANE_YELLOW);
		registerBlock("quartz_glass_pane_lime", QUARTZ_GLASS_PANE_LIME);
		registerBlock("quartz_glass_pane_pink", QUARTZ_GLASS_PANE_PINK);
		registerBlock("quartz_glass_pane_gray", QUARTZ_GLASS_PANE_GRAY);
		registerBlock("quartz_glass_pane_light_gray", QUARTZ_GLASS_PANE_LIGHT_GRAY);
		registerBlock("quartz_glass_pane_cyan", QUARTZ_GLASS_PANE_CYAN);
		registerBlock("quartz_glass_pane_purple", QUARTZ_GLASS_PANE_PURPLE);
		registerBlock("quartz_glass_pane_blue", QUARTZ_GLASS_PANE_BLUE);
		registerBlock("quartz_glass_pane_brown", QUARTZ_GLASS_PANE_BROWN);
		registerBlock("quartz_glass_pane_green", QUARTZ_GLASS_PANE_GREEN);
		registerBlock("quartz_glass_pane_red", QUARTZ_GLASS_PANE_RED);
		registerBlock("quartz_glass_pane_black", QUARTZ_GLASS_PANE_BLACK);
		registerBlock("quartz_glass_framed_pane_white", QUARTZ_GLASS_FRAMED_PANE_WHITE);
		registerBlock("quartz_glass_framed_pane_orange", QUARTZ_GLASS_FRAMED_PANE_ORANGE);
		registerBlock("quartz_glass_framed_pane_magenta", QUARTZ_GLASS_FRAMED_PANE_MAGENTA);
		registerBlock("quartz_glass_framed_pane_light_blue", QUARTZ_GLASS_FRAMED_PANE_LIGHT_BLUE);
		registerBlock("quartz_glass_framed_pane_yellow", QUARTZ_GLASS_FRAMED_PANE_YELLOW);
		registerBlock("quartz_glass_framed_pane_lime", QUARTZ_GLASS_FRAMED_PANE_LIME);
		registerBlock("quartz_glass_framed_pane_pink", QUARTZ_GLASS_FRAMED_PANE_PINK);
		registerBlock("quartz_glass_framed_pane_gray", QUARTZ_GLASS_FRAMED_PANE_GRAY);
		registerBlock("quartz_glass_framed_pane_light_gray", QUARTZ_GLASS_FRAMED_PANE_LIGHT_GRAY);
		registerBlock("quartz_glass_framed_pane_cyan", QUARTZ_GLASS_FRAMED_PANE_CYAN);
		registerBlock("quartz_glass_framed_pane_purple", QUARTZ_GLASS_FRAMED_PANE_PURPLE);
		registerBlock("quartz_glass_framed_pane_blue", QUARTZ_GLASS_FRAMED_PANE_BLUE);
		registerBlock("quartz_glass_framed_pane_brown", QUARTZ_GLASS_FRAMED_PANE_BROWN);
		registerBlock("quartz_glass_framed_pane_green", QUARTZ_GLASS_FRAMED_PANE_GREEN);
		registerBlock("quartz_glass_framed_pane_red", QUARTZ_GLASS_FRAMED_PANE_RED);
		registerBlock("quartz_glass_framed_pane_black", QUARTZ_GLASS_FRAMED_PANE_BLACK);
		registerBlockNI("soul_lily", SOUL_LILY);
		registerBlock("soul_lily_sapling", SOUL_LILY_SAPLING);
		registerBlock("soul_grass", SOUL_GRASS);
		registerBlock("wart_log", WART_LOG);
		registerBlock("wart_bark", WART_BARK);
		registerBlockNI("wart_roots", WART_ROOTS);
		registerBlock("wall_moss", WALL_MOSS);
		registerBlock("wall_mushroom_brown", WALL_MUSHROOM_BROWN);
		registerBlock("wall_mushroom_red", WALL_MUSHROOM_RED);
		registerBlock("roof_tile_reeds", ROOF_TILE_REEDS);
		registerBlock("roof_tile_reeds_stairs", ROOF_TILE_REEDS_STAIRS);
		registerBlock("roof_tile_reeds_slab", ROOF_TILE_REEDS_SLAB);
		registerBlock("roof_tile_stalagnate", ROOF_TILE_STALAGNATE);
		registerBlock("roof_tile_stalagnate_stairs", ROOF_TILE_STALAGNATE_STAIRS);
		registerBlock("roof_tile_stalagnate_slab", ROOF_TILE_STALAGNATE_SLAB);
		registerBlock("roof_tile_nether_bricks", ROOF_TILE_NETHER_BRICKS);
		registerBlock("roof_tile_nether_bricks_stairs", ROOF_TILE_NETHER_BRICKS_STAIRS);
		registerBlock("roof_tile_nether_bricks_slab", ROOF_TILE_NETHER_BRICKS_SLAB);
		registerBlock("roof_tile_cincinnasite", ROOF_TILE_CINCINNASITE);
		registerBlock("roof_tile_cincinnasite_stairs", ROOF_TILE_CINCINNASITE_STAIRS);
		registerBlock("roof_tile_cincinnasite_slab", ROOF_TILE_CINCINNASITE_SLAB);
		registerBlock("roof_tile_willow", ROOF_TILE_WILLOW);
		registerBlock("roof_tile_willow_stairs", ROOF_TILE_WILLOW_STAIRS);
		registerBlock("roof_tile_willow_slab", ROOF_TILE_WILLOW_SLAB);
		registerBlock("roof_tile_wart", ROOF_TILE_WART);
		registerBlock("roof_tile_wart_stairs", ROOF_TILE_WART_STAIRS);
		registerBlock("roof_tile_wart_slab", ROOF_TILE_WART_SLAB);
		registerBlock("taburet_reeds", TABURET_REEDS);
		registerBlock("taburet_stalagnate", TABURET_STALAGNATE);
		registerBlock("taburet_willow", TABURET_WILLOW);
		registerBlock("taburet_wart", TABURET_WART);
		registerBlock("taburet_cincinnasite", TABURET_CINCINNASITE);
		registerBlock("stalagnate_ladder", STALAGNATE_LADDER);
		registerBlock("willow_ladder", WILLOW_LADDER);
		registerBlock("wart_ladder", WART_LADDER);
		
		registerBlock("chair_reeds", CHAIR_REEDS);
		registerBlock("chair_stalagnate", CHAIR_STALAGNATE);
		registerBlock("chair_willow", CHAIR_WILLOW);
		registerBlock("chair_wart", CHAIR_WART);
		registerBlock("chair_cincinnasite", CHAIR_CINCINNASITE);
		
		registerBlock("bar_stool_reeds", BAR_STOOL_REEDS);
		registerBlock("bar_stool_stalagnate", BAR_STOOL_STALAGNATE);
		registerBlock("bar_stool_willow", BAR_STOOL_WILLOW);
		registerBlock("bar_stool_wart", BAR_STOOL_WART);
		registerBlock("bar_stool_cincinnasite", BAR_STOOL_CINCINNASITE);
		
		registerBlock("striped_log_stalagnate", STRIPED_LOG_STALAGNATE);
		registerBlock("striped_log_willow", STRIPED_LOG_WILLOW);
		registerBlock("striped_log_wart", STRIPED_LOG_WART);
		
		registerBlock("striped_bark_stalagnate", STRIPED_BARK_STALAGNATE);
		registerBlock("striped_bark_willow", STRIPED_BARK_WILLOW);
		registerBlock("striped_bark_wart", STRIPED_BARK_WART);
		
		registerBlockNI("giant_mold", GIANT_MOLD);
		registerBlock("giant_mold_sapling", GIANT_MOLD_SAPLING);
		
		registerBlockNI("mushroom_fir", MUSHROOM_FIR);
		registerBlock("mushroom_fir_sapling", MUSHROOM_FIR_SAPLING);
	}
	
	private static void registerBlock(String name, Block block)
	{
		if (Config.getBoolean("blocks", name, true))
		{
			Registry.register(Registry.BLOCK, new Identifier(BetterNether.MOD_ID, name), block);
			ItemsRegister.RegisterItem(name, new BlockItem(block, new Item.Settings().group(CreativeTab.BN_TAB)));
		}
	}
	
	private static void registerBlockNI(String name, Block block)
	{
		if (Config.getBoolean("blocks", name, true))
		{
			Registry.register(Registry.BLOCK, new Identifier(BetterNether.MOD_ID, name), block);
		}
	}
}
