package paulevs.betternether.registers;

import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.block.MaterialColor;
import net.minecraft.block.PressurePlateBlock.ActivationRule;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;
import paulevs.betternether.BetterNether;
import paulevs.betternether.blocks.BNBoneBlock;
import paulevs.betternether.blocks.BNButton;
import paulevs.betternether.blocks.BNDoor;
import paulevs.betternether.blocks.BNFence;
import paulevs.betternether.blocks.BNGate;
import paulevs.betternether.blocks.BNGlass;
import paulevs.betternether.blocks.BNLadder;
import paulevs.betternether.blocks.BNNetherBrick;
import paulevs.betternether.blocks.BNPane;
import paulevs.betternether.blocks.BNPillar;
import paulevs.betternether.blocks.BNPlanks;
import paulevs.betternether.blocks.BNPlate;
import paulevs.betternether.blocks.BNSlab;
import paulevs.betternether.blocks.BNStairs;
import paulevs.betternether.blocks.BNTrapdoor;
import paulevs.betternether.blocks.BNWall;
import paulevs.betternether.blocks.BlockAgave;
import paulevs.betternether.blocks.BlockBarrelCactus;
import paulevs.betternether.blocks.BlockBlackApple;
import paulevs.betternether.blocks.BlockBlackAppleSeed;
import paulevs.betternether.blocks.BlockBlackBush;
import paulevs.betternether.blocks.BlockBlackVine;
import paulevs.betternether.blocks.BlockBoneMushroom;
import paulevs.betternether.blocks.BlockBrownLargeMushroom;
import paulevs.betternether.blocks.BlockChestOfDrawers;
import paulevs.betternether.blocks.BlockCincinnasitFireBowl;
import paulevs.betternether.blocks.BlockCincinnasitPillar;
import paulevs.betternether.blocks.BlockCincinnasite;
import paulevs.betternether.blocks.BlockCincinnasiteFrame;
import paulevs.betternether.blocks.BlockCincinnasiteLantern;
import paulevs.betternether.blocks.BlockCincinnasiteOre;
import paulevs.betternether.blocks.BlockCincinnasitePedestal;
import paulevs.betternether.blocks.BlockCincinnasitePot;
import paulevs.betternether.blocks.BlockEggPlant;
import paulevs.betternether.blocks.BlockEyeSeed;
import paulevs.betternether.blocks.BlockEyeVine;
import paulevs.betternether.blocks.BlockEyeball;
import paulevs.betternether.blocks.BlockEyeballSmall;
import paulevs.betternether.blocks.BlockFarmland;
import paulevs.betternether.blocks.BlockGeyser;
import paulevs.betternether.blocks.BlockGoldenVine;
import paulevs.betternether.blocks.BlockGrayMold;
import paulevs.betternether.blocks.BlockInkBush;
import paulevs.betternether.blocks.BlockInkBushSeed;
import paulevs.betternether.blocks.BlockLucisMushroom;
import paulevs.betternether.blocks.BlockLucisSpore;
import paulevs.betternether.blocks.BlockMagmaFlower;
import paulevs.betternether.blocks.BlockNetherCactus;
import paulevs.betternether.blocks.BlockNetherGrass;
import paulevs.betternether.blocks.BlockNetherMycelium;
import paulevs.betternether.blocks.BlockNetherReed;
import paulevs.betternether.blocks.BlockNetherrackFurnace;
import paulevs.betternether.blocks.BlockNetherrackMoss;
import paulevs.betternether.blocks.BlockOrangeMushroom;
import paulevs.betternether.blocks.BlockPottedPlant;
import paulevs.betternether.blocks.BlockRedLargeMushroom;
import paulevs.betternether.blocks.BlockRedMold;
import paulevs.betternether.blocks.BlockReedsBlock;
import paulevs.betternether.blocks.BlockSmallLantern;
import paulevs.betternether.blocks.BlockSmoker;
import paulevs.betternether.blocks.BlockSoulLily;
import paulevs.betternether.blocks.BlockSoulLilySapling;
import paulevs.betternether.blocks.BlockSoulVein;
import paulevs.betternether.blocks.BlockStalagnate;
import paulevs.betternether.blocks.BlockStalagnateBark;
import paulevs.betternether.blocks.BlockStalagnateBowl;
import paulevs.betternether.blocks.BlockStalagnateSeed;
import paulevs.betternether.blocks.BlockStalagnateStem;
import paulevs.betternether.blocks.BlockVeinedSand;
import paulevs.betternether.blocks.BlockWartSeed;
import paulevs.betternether.blocks.BlockWillowBark;
import paulevs.betternether.blocks.BlockWillowBranch;
import paulevs.betternether.blocks.BlockWillowLeaves;
import paulevs.betternether.blocks.BlockWillowLog;
import paulevs.betternether.blocks.BlockWillowSapling;
import paulevs.betternether.blocks.BlockWillowTrunk;
import paulevs.betternether.blocks.CincinnasiteForge;
import paulevs.betternether.blocks.PigStatueRespawner;
import paulevs.betternether.config.Config;
import paulevs.betternether.tab.CreativeTab;

public class BlocksRegister
{
	public static final Block BLOCK_EYEBALL = new BlockEyeball();
	public static final Block BLOCK_EYEBALL_SMALL = new BlockEyeballSmall();
	public static final Block BLOCK_EYE_VINE = new BlockEyeVine();
	public static final Block BLOCK_EYE_SEED = new BlockEyeSeed();
	public static final Block BLOCK_NETHERRACK_MOSS = new BlockNetherrackMoss();
	public static final Block BLOCK_NETHER_GRASS = new BlockNetherGrass();
	public static final Block BLOCK_NETHER_REED = new BlockNetherReed();
	public static final Block BLOCK_STALAGNATE_STEM = new BlockStalagnateStem();
	public static final Block BLOCK_STALAGNATE = new BlockStalagnate();
	public static final Block BLOCK_STALAGNATE_SEED = new BlockStalagnateSeed();
	public static final Block BLOCK_STALAGNATE_BARK = new BlockStalagnateBark();
	public static final Block BLOCK_STALAGNATE_PLANKS = new BNPlanks(MaterialColor.LIME_TERRACOTTA);
	public static final Block BLOCK_STALAGNATE_PLANKS_STAIRS = new BNStairs(BLOCK_STALAGNATE_PLANKS);
	public static final Block BLOCK_STALAGNATE_PLANKS_SLAB = new BNSlab(BLOCK_STALAGNATE_PLANKS);
	public static final Block BLOCK_STALAGNATE_PLANKS_FENCE = new BNFence(BLOCK_STALAGNATE_PLANKS);
	public static final Block BLOCK_STALAGNATE_PLANKS_GATE = new BNGate(BLOCK_STALAGNATE_PLANKS);
	public static final Block BLOCK_STALAGNATE_PLANKS_BUTTON = new BNButton(BLOCK_STALAGNATE_PLANKS);
	public static final Block BLOCK_STALAGNATE_PLANKS_PLATE = new BNPlate(ActivationRule.EVERYTHING, BLOCK_STALAGNATE_PLANKS);
	public static final Block BLOCK_STALAGNATE_PLANKS_TRAPDOOR = new BNTrapdoor(BLOCK_STALAGNATE_PLANKS);
	public static final Block BLOCK_STALAGNATE_PLANKS_DOOR = new BNDoor(BLOCK_STALAGNATE_PLANKS);
	public static final Block BLOCK_REEDS_BLOCK = new BlockReedsBlock();
	public static final Block BLOCK_REEDS_STAIRS = new BNStairs(BLOCK_REEDS_BLOCK);
	public static final Block BLOCK_REEDS_SLAB = new BNSlab(BLOCK_REEDS_BLOCK);
	public static final Block BLOCK_REEDS_FENCE = new BNFence(BLOCK_REEDS_BLOCK);
	public static final Block BLOCK_REEDS_GATE = new BNGate(BLOCK_REEDS_BLOCK);
	public static final Block BLOCK_REEDS_BUTTON = new BNButton(BLOCK_REEDS_BLOCK);
	public static final Block BLOCK_REEDS_PLATE = new BNPlate(ActivationRule.EVERYTHING, BLOCK_REEDS_BLOCK);
	public static final Block BLOCK_REEDS_TRAPDOOR = new BNTrapdoor(BLOCK_REEDS_BLOCK);
	public static final Block BLOCK_REEDS_DOOR = new BNDoor(BLOCK_REEDS_BLOCK);
	public static final Block BLOCK_LUCIS_MUSHROOM = new BlockLucisMushroom();
	public static final Block BLOCK_LUCIS_SPORE = new BlockLucisSpore();
	public static final Block BLOCK_NETHER_CACTUS = new BlockNetherCactus();
	public static final Block BLOCK_WART_SEED = new BlockWartSeed();
	public static final Block BLOCK_BARREL_CACTUS = new BlockBarrelCactus();
	public static final Block BLOCK_AGAVE = new BlockAgave();
	public static final Block BLOCK_BLACK_BUSH = new BlockBlackBush();
	public static final Block BLOCK_INK_BUSH = new BlockInkBush();
	public static final Block BLOCK_INK_BUSH_SEED = new BlockInkBushSeed();
	public static final Block BLOCK_SMOKER = new BlockSmoker();
	public static final Block BLOCK_EGG_PLANT = new BlockEggPlant();
	public static final Block BLOCK_BLACK_APPLE = new BlockBlackApple();
	public static final Block BLOCK_BLACK_APPLE_SEED = new BlockBlackAppleSeed();
	public static final Block BLOCK_MAGMA_FLOWER = new BlockMagmaFlower();
	public static final Block BLOCK_NETHER_MYCELIUM = new BlockNetherMycelium();
	public static final Block BLOCK_RED_LARGE_MUSHROOM = new BlockRedLargeMushroom();
	public static final Block BLOCK_BROWN_LARGE_MUSHROOM = new BlockBrownLargeMushroom();
	public static final Block BLOCK_ORANGE_MUSHROOM = new BlockOrangeMushroom();
	public static final Block BLOCK_RED_MOLD = new BlockRedMold();
	public static final Block BLOCK_GRAY_MOLD = new BlockGrayMold();
	public static final Block BLOCK_CINCINNASITE_ORE = new BlockCincinnasiteOre();
	public static final Block BLOCK_CINCINNASITE = new BlockCincinnasite();
	public static final Block BLOCK_CINCINNASITE_FORGED = new BlockCincinnasite();
	public static final Block BLOCK_CINCINNASITE_PILLAR = new BlockCincinnasitPillar();
	public static final Block BLOCK_CINCINNASITE_BRICKS = new BlockCincinnasite();
	public static final Block BLOCK_CINCINNASITE_BRICK_PLATE = new BlockCincinnasite();
	public static final Block BLOCK_CINCINNASITE_STAIRS = new BNStairs(BLOCK_CINCINNASITE);
	public static final Block BLOCK_CINCINNASITE_SLAB = new BNSlab(BLOCK_CINCINNASITE);
	public static final Block BLOCK_CINCINNASITE_BUTTON = new BNButton(BLOCK_CINCINNASITE);
	public static final Block BLOCK_CINCINNASITE_PLATE = new BNPlate(ActivationRule.MOBS, BLOCK_CINCINNASITE);
	public static final Block BLOCK_CINCINNASITE_LANTERN = new BlockCincinnasiteLantern();
	public static final Block BLOCK_CINCINNASITE_TILE_LARGE = new BlockCincinnasite();
	public static final Block BLOCK_CINCINNASITE_TILE_SMALL = new BlockCincinnasite();
	public static final Block BLOCK_CINCINNASITE_CARVED = new BlockCincinnasite();
	public static final Block BLOCK_NETHER_BRICK_TILE_LARGE = new BNNetherBrick();
	public static final Block BLOCK_NETHER_BRICK_TILE_SMALL = new BNNetherBrick();
	public static final Block BLOCK_CINCINNASITE_WALL = new BNWall(BLOCK_CINCINNASITE);
	public static final Block BLOCK_BONE = new BNBoneBlock();
	public static final Block BLOCK_BONE_STAIRS = new BNStairs(BLOCK_BONE);
	public static final Block BLOCK_BONE_SLAB = new BNSlab(BLOCK_BONE);
	public static final Block BLOCK_BONE_BUTTON = new BNButton(BLOCK_BONE);
	public static final Block BLOCK_BONE_PLATE = new BNPlate(ActivationRule.EVERYTHING, BLOCK_BONE);
	public static final Block BLOCK_CINCINNASITE_FIRE_BOWL = new BlockCincinnasitFireBowl();
	public static final Block BLOCK_BONE_WALL = new BNWall(BLOCK_BONE);
	public static final Block BLOCK_NETHER_BRICK_WALL = new BNWall(Blocks.NETHER_BRICKS);
	public static final Block BLOCK_NETHER_BRICK_TILE_SLAB = new BNSlab(BLOCK_NETHER_BRICK_TILE_SMALL);
	public static final Block BLOCK_NETHER_BRICK_TILE_STAIRS = new BNStairs(BLOCK_NETHER_BRICK_TILE_SMALL);
	public static final Block BLOCK_BONE_MUSHROOM = new BlockBoneMushroom();
	public static final Block BLOCK_REEDS_LADDER = new BNLadder(BLOCK_REEDS_BLOCK);
	public static final Block BLOCK_CINCINNASITE_BRICKS_PILLAR = new BNPillar(BLOCK_CINCINNASITE);
	public static final Block BLOCK_BONE_TILE = new BNBoneBlock();
	public static final Block BLOCK_CINCINNASITE_PEDESTAL = new BlockCincinnasitePedestal();
	public static final Block BLOCK_PIG_STATUE_RESPAWNER = new PigStatueRespawner();
	public static final Block BLOCK_CINCINNASITE_POT = new BlockCincinnasitePot();
	public static final Block BLOCK_POTTED_PLANT = new BlockPottedPlant();
	public static final Block BLOCK_CINCINNASITE_FRAME = new BlockCincinnasiteFrame();
	public static final Block BLOCK_QUARTZ_GLASS = new BNGlass(Blocks.GLASS);
	public static final Block BLOCK_QUARTZ_GLASS_FRAMED = new BNGlass(BLOCK_CINCINNASITE);
	public static final Block BLOCK_QUARTZ_WHITE_GLASS = new BNGlass(BLOCK_QUARTZ_GLASS);
	public static final Block BLOCK_QUARTZ_ORANGE_GLASS = new BNGlass(BLOCK_QUARTZ_GLASS);
	public static final Block BLOCK_QUARTZ_MAGENTA_GLASS = new BNGlass(BLOCK_QUARTZ_GLASS);
	public static final Block BLOCK_QUARTZ_LIGHT_BLUE_GLASS = new BNGlass(BLOCK_QUARTZ_GLASS);
	public static final Block BLOCK_QUARTZ_YELLOW_GLASS = new BNGlass(BLOCK_QUARTZ_GLASS);
	public static final Block BLOCK_QUARTZ_LIME_GLASS = new BNGlass(BLOCK_QUARTZ_GLASS);
	public static final Block BLOCK_QUARTZ_PINK_GLASS = new BNGlass(BLOCK_QUARTZ_GLASS);
	public static final Block BLOCK_QUARTZ_GRAY_GLASS = new BNGlass(BLOCK_QUARTZ_GLASS);
	public static final Block BLOCK_QUARTZ_LIGHT_GRAY_GLASS = new BNGlass(BLOCK_QUARTZ_GLASS);
	public static final Block BLOCK_QUARTZ_CYAN_GLASS = new BNGlass(BLOCK_QUARTZ_GLASS);
	public static final Block BLOCK_QUARTZ_PURPLE_GLASS = new BNGlass(BLOCK_QUARTZ_GLASS);
	public static final Block BLOCK_QUARTZ_BLUE_GLASS = new BNGlass(BLOCK_QUARTZ_GLASS);
	public static final Block BLOCK_QUARTZ_BROWN_GLASS = new BNGlass(BLOCK_QUARTZ_GLASS);
	public static final Block BLOCK_QUARTZ_GREEN_GLASS = new BNGlass(BLOCK_QUARTZ_GLASS);
	public static final Block BLOCK_QUARTZ_RED_GLASS = new BNGlass(BLOCK_QUARTZ_GLASS);
	public static final Block BLOCK_QUARTZ_BLACK_GLASS = new BNGlass(BLOCK_QUARTZ_GLASS);
	public static final Block BLOCK_CINCINNASITE_BARS = new BNPane(BLOCK_CINCINNASITE, true);
	public static final Block BLOCK_QUARTZ_GLASS_PANE = new BNPane(BLOCK_QUARTZ_GLASS, true);
	public static final Block BLOCK_QUARTZ_GLASS_FRAMED_PANE = new BNPane(BLOCK_CINCINNASITE, true);
	public static final Block BLOCK_CINCINNASITE_FORGE = new CincinnasiteForge();
	public static final Block BLOCK_NETHERRACK_FURNACE = new BlockNetherrackFurnace();
	public static final Block BLOCK_BONE_REED_DOOR = new BNDoor(BLOCK_BONE);
	public static final Block BLOCK_BONE_CINCINNASITE_DOOR = new BNDoor(BLOCK_BONE);
	public static final Block BLOCK_QUARTZ_GLASS_FRAMED_WHITE = new BNGlass(BLOCK_QUARTZ_GLASS_FRAMED);
	public static final Block BLOCK_QUARTZ_GLASS_FRAMED_ORANGE = new BNGlass(BLOCK_QUARTZ_GLASS_FRAMED);
	public static final Block BLOCK_QUARTZ_GLASS_FRAMED_MAGENTA = new BNGlass(BLOCK_QUARTZ_GLASS_FRAMED);
	public static final Block BLOCK_QUARTZ_GLASS_FRAMED_LIGHT_BLUE = new BNGlass(BLOCK_QUARTZ_GLASS_FRAMED);
	public static final Block BLOCK_QUARTZ_GLASS_FRAMED_YELLOW = new BNGlass(BLOCK_QUARTZ_GLASS_FRAMED);
	public static final Block BLOCK_QUARTZ_GLASS_FRAMED_LIME = new BNGlass(BLOCK_QUARTZ_GLASS_FRAMED);
	public static final Block BLOCK_QUARTZ_GLASS_FRAMED_PINK = new BNGlass(BLOCK_QUARTZ_GLASS_FRAMED);
	public static final Block BLOCK_QUARTZ_GLASS_FRAMED_GRAY = new BNGlass(BLOCK_QUARTZ_GLASS_FRAMED);
	public static final Block BLOCK_QUARTZ_GLASS_FRAMED_LIGHT_GRAY = new BNGlass(BLOCK_QUARTZ_GLASS_FRAMED);
	public static final Block BLOCK_QUARTZ_GLASS_FRAMED_CYAN = new BNGlass(BLOCK_QUARTZ_GLASS_FRAMED);
	public static final Block BLOCK_QUARTZ_GLASS_FRAMED_PURPLE = new BNGlass(BLOCK_QUARTZ_GLASS_FRAMED);
	public static final Block BLOCK_QUARTZ_GLASS_FRAMED_BLUE = new BNGlass(BLOCK_QUARTZ_GLASS_FRAMED);
	public static final Block BLOCK_QUARTZ_GLASS_FRAMED_BROWN = new BNGlass(BLOCK_QUARTZ_GLASS_FRAMED);
	public static final Block BLOCK_QUARTZ_GLASS_FRAMED_GREEN = new BNGlass(BLOCK_QUARTZ_GLASS_FRAMED);
	public static final Block BLOCK_QUARTZ_GLASS_FRAMED_RED = new BNGlass(BLOCK_QUARTZ_GLASS_FRAMED);
	public static final Block BLOCK_QUARTZ_GLASS_FRAMED_BLACK = new BNGlass(BLOCK_QUARTZ_GLASS_FRAMED);
	public static final Block BLOCK_STALAGNATE_BOWL = new BlockStalagnateBowl();
	public static final Block BLOCK_CHEST_OF_DRAWERS = new BlockChestOfDrawers();
	public static final Block FARMLAND = new BlockFarmland();
	public static final Block WILLOW_BRANCH = new BlockWillowBranch();
	public static final Block WILLOW_LEAVES = new BlockWillowLeaves();
	public static final Block WILLOW_TRUNK = new BlockWillowTrunk();
	public static final Block WILLOW_LOG = new BlockWillowLog();
	public static final Block WILLOW_BARK = new BlockWillowBark();
	public static final Block WILLOW_SAPLING = new BlockWillowSapling();
	public static final Block SWAMP_GRASS = new BlockNetherGrass();
	public static final Block WILLOW_PLANKS = new BNPlanks(MaterialColor.RED_TERRACOTTA);
	public static final Block BLOCK_WILLOW_STAIRS = new BNStairs(WILLOW_PLANKS);
	public static final Block BLOCK_WILLOW_SLAB = new BNSlab(WILLOW_PLANKS);
	public static final Block BLOCK_WILLOW_FENCE = new BNFence(WILLOW_PLANKS);
	public static final Block BLOCK_WILLOW_GATE = new BNGate(WILLOW_PLANKS);
	public static final Block BLOCK_WILLOW_BUTTON = new BNButton(WILLOW_PLANKS);
	public static final Block BLOCK_WILLOW_PLATE = new BNPlate(ActivationRule.EVERYTHING, WILLOW_PLANKS);
	public static final Block BLOCK_WILLOW_TRAPDOOR = new BNTrapdoor(WILLOW_PLANKS);
	public static final Block BLOCK_WILLOW_DOOR = new BNDoor(WILLOW_PLANKS);
	public static final Block WART_PLANKS = new BNPlanks(MaterialColor.RED);
	public static final Block BLOCK_WART_STAIRS = new BNStairs(WART_PLANKS);
	public static final Block BLOCK_WART_SLAB = new BNSlab(WART_PLANKS);
	public static final Block BLOCK_WART_FENCE = new BNFence(WART_PLANKS);
	public static final Block BLOCK_WART_GATE = new BNGate(WART_PLANKS);
	public static final Block BLOCK_WART_BUTTON = new BNButton(WART_PLANKS);
	public static final Block BLOCK_WART_PLATE = new BNPlate(ActivationRule.EVERYTHING, WART_PLANKS);
	public static final Block BLOCK_WART_TRAPDOOR = new BNTrapdoor(WART_PLANKS);
	public static final Block BLOCK_WART_DOOR = new BNDoor(WART_PLANKS);
	public static final Block BLOCK_BLACK_VINE = new BlockBlackVine();
	public static final Block BLOCK_VEINED_SAND = new BlockVeinedSand();
	public static final Block BLOCK_SOUL_VEIN = new BlockSoulVein();
	public static final Block BLOCK_BLOOMING_VINE = new BlockBlackVine();
	public static final Block BLOCK_GOLDEN_VINE = new BlockGoldenVine();
	public static final Block BLOCK_GEYSER = new BlockGeyser();
	public static final Block MUSHROOM_STEM = new BlockStalagnateStem();
	public static final Block MUSHROOM_PLANKS = new BNPlanks(MaterialColor.LIGHT_GRAY);
	public static final Block MUSHROOM_STAIRS = new BNStairs(MUSHROOM_PLANKS);
	public static final Block MUSHROOM_SLAB = new BNSlab(MUSHROOM_PLANKS);
	public static final Block MUSHROOM_FENCE = new BNFence(MUSHROOM_PLANKS);
	public static final Block MUSHROOM_GATE = new BNGate(MUSHROOM_PLANKS);
	public static final Block MUSHROOM_BUTTON = new BNButton(MUSHROOM_PLANKS);
	public static final Block MUSHROOM_PLATE = new BNPlate(ActivationRule.EVERYTHING, MUSHROOM_PLANKS);
	public static final Block MUSHROOM_TRAPDOOR = new BNTrapdoor(MUSHROOM_STAIRS);
	public static final Block MUSHROOM_DOOR = new BNDoor(MUSHROOM_STAIRS);
	public static final Block CINCINNASITE_LANTERN_SMALL = new BlockSmallLantern();
	public static final Block BLOCK_QUARTZ_GLASS_PANE_WHITE = new BNPane(BLOCK_QUARTZ_GLASS, false);
	public static final Block BLOCK_QUARTZ_GLASS_PANE_ORANGE = new BNPane(BLOCK_QUARTZ_GLASS, false);
	public static final Block BLOCK_QUARTZ_GLASS_PANE_MAGENTA = new BNPane(BLOCK_QUARTZ_GLASS, false);
	public static final Block BLOCK_QUARTZ_GLASS_PANE_LIGHT_BLUE = new BNPane(BLOCK_QUARTZ_GLASS, false);
	public static final Block BLOCK_QUARTZ_GLASS_PANE_YELLOW = new BNPane(BLOCK_QUARTZ_GLASS, false);
	public static final Block BLOCK_QUARTZ_GLASS_PANE_LIME = new BNPane(BLOCK_QUARTZ_GLASS, false);
	public static final Block BLOCK_QUARTZ_GLASS_PANE_PINK = new BNPane(BLOCK_QUARTZ_GLASS, false);
	public static final Block BLOCK_QUARTZ_GLASS_PANE_GRAY = new BNPane(BLOCK_QUARTZ_GLASS, false);
	public static final Block BLOCK_QUARTZ_GLASS_PANE_LIGHT_GRAY = new BNPane(BLOCK_QUARTZ_GLASS, false);
	public static final Block BLOCK_QUARTZ_GLASS_PANE_CYAN = new BNPane(BLOCK_QUARTZ_GLASS, false);
	public static final Block BLOCK_QUARTZ_GLASS_PANE_PURPLE = new BNPane(BLOCK_QUARTZ_GLASS, false);
	public static final Block BLOCK_QUARTZ_GLASS_PANE_BLUE = new BNPane(BLOCK_QUARTZ_GLASS, false);
	public static final Block BLOCK_QUARTZ_GLASS_PANE_BROWN = new BNPane(BLOCK_QUARTZ_GLASS, false);
	public static final Block BLOCK_QUARTZ_GLASS_PANE_GREEN = new BNPane(BLOCK_QUARTZ_GLASS, false);
	public static final Block BLOCK_QUARTZ_GLASS_PANE_RED = new BNPane(BLOCK_QUARTZ_GLASS, false);
	public static final Block BLOCK_QUARTZ_GLASS_PANE_BLACK = new BNPane(BLOCK_QUARTZ_GLASS, false);
	public static final Block BLOCK_QUARTZ_GLASS_FRAMED_PANE_WHITE = new BNPane(BLOCK_QUARTZ_GLASS_FRAMED, true);
	public static final Block BLOCK_QUARTZ_GLASS_FRAMED_PANE_ORANGE = new BNPane(BLOCK_QUARTZ_GLASS_FRAMED, true);
	public static final Block BLOCK_QUARTZ_GLASS_FRAMED_PANE_MAGENTA = new BNPane(BLOCK_QUARTZ_GLASS_FRAMED, true);
	public static final Block BLOCK_QUARTZ_GLASS_FRAMED_PANE_LIGHT_BLUE = new BNPane(BLOCK_QUARTZ_GLASS_FRAMED, true);
	public static final Block BLOCK_QUARTZ_GLASS_FRAMED_PANE_YELLOW = new BNPane(BLOCK_QUARTZ_GLASS_FRAMED, true);
	public static final Block BLOCK_QUARTZ_GLASS_FRAMED_PANE_LIME = new BNPane(BLOCK_QUARTZ_GLASS_FRAMED, true);
	public static final Block BLOCK_QUARTZ_GLASS_FRAMED_PANE_PINK = new BNPane(BLOCK_QUARTZ_GLASS_FRAMED, true);
	public static final Block BLOCK_QUARTZ_GLASS_FRAMED_PANE_GRAY = new BNPane(BLOCK_QUARTZ_GLASS_FRAMED, true);
	public static final Block BLOCK_QUARTZ_GLASS_FRAMED_PANE_LIGHT_GRAY = new BNPane(BLOCK_QUARTZ_GLASS_FRAMED, true);
	public static final Block BLOCK_QUARTZ_GLASS_FRAMED_PANE_CYAN = new BNPane(BLOCK_QUARTZ_GLASS_FRAMED, true);
	public static final Block BLOCK_QUARTZ_GLASS_FRAMED_PANE_PURPLE = new BNPane(BLOCK_QUARTZ_GLASS_FRAMED, true);
	public static final Block BLOCK_QUARTZ_GLASS_FRAMED_PANE_BLUE = new BNPane(BLOCK_QUARTZ_GLASS_FRAMED, true);
	public static final Block BLOCK_QUARTZ_GLASS_FRAMED_PANE_BROWN = new BNPane(BLOCK_QUARTZ_GLASS_FRAMED, true);
	public static final Block BLOCK_QUARTZ_GLASS_FRAMED_PANE_GREEN = new BNPane(BLOCK_QUARTZ_GLASS_FRAMED, true);
	public static final Block BLOCK_QUARTZ_GLASS_FRAMED_PANE_RED = new BNPane(BLOCK_QUARTZ_GLASS_FRAMED, true);
	public static final Block BLOCK_QUARTZ_GLASS_FRAMED_PANE_BLACK = new BNPane(BLOCK_QUARTZ_GLASS_FRAMED, true);
	public static final Block BLOCK_SOUL_LILY = new BlockSoulLily();
	public static final Block BLOCK_SOUL_LILY_SAPLING = new BlockSoulLilySapling();
	
	public static void register()
	{
		registerBlock("block_eyeball", BLOCK_EYEBALL);
		registerBlock("block_eyeball_small", BLOCK_EYEBALL_SMALL);
		registerBlockNI("eye_vine", BLOCK_EYE_VINE);
		registerBlock("eye_seed", BLOCK_EYE_SEED);
		registerBlock("netherrack_moss", BLOCK_NETHERRACK_MOSS);
		registerBlock("nether_grass", BLOCK_NETHER_GRASS);
		registerBlock("nether_reed", BLOCK_NETHER_REED);
		registerBlock("stalagnate_stem", BLOCK_STALAGNATE_STEM);
		registerBlockNI("stalagnate", BLOCK_STALAGNATE);
		registerBlock("stalagnate_seed", BLOCK_STALAGNATE_SEED);
		registerBlock("stalagnate_bark", BLOCK_STALAGNATE_BARK);
		registerBlock("stalagnate_planks", BLOCK_STALAGNATE_PLANKS);
		registerBlock("stalagnate_planks_stairs", BLOCK_STALAGNATE_PLANKS_STAIRS);
		registerBlock("stalagnate_planks_slab", BLOCK_STALAGNATE_PLANKS_SLAB);
		registerBlock("stalagnate_planks_fence", BLOCK_STALAGNATE_PLANKS_FENCE);
		registerBlock("stalagnate_planks_gate", BLOCK_STALAGNATE_PLANKS_GATE);
		registerBlock("stalagnate_planks_button", BLOCK_STALAGNATE_PLANKS_BUTTON);
		registerBlock("stalagnate_planks_plate", BLOCK_STALAGNATE_PLANKS_PLATE);
		registerBlock("stalagnate_planks_trapdoor", BLOCK_STALAGNATE_PLANKS_TRAPDOOR);
		registerBlock("stalagnate_planks_door", BLOCK_STALAGNATE_PLANKS_DOOR);
		registerBlock("reeds_block", BLOCK_REEDS_BLOCK);
		registerBlock("reeds_stairs", BLOCK_REEDS_STAIRS);
		registerBlock("reeds_slab", BLOCK_REEDS_SLAB);
		registerBlock("reeds_fence", BLOCK_REEDS_FENCE);
		registerBlock("reeds_gate", BLOCK_REEDS_GATE);
		registerBlock("reeds_button", BLOCK_REEDS_BUTTON);
		registerBlock("reeds_plate", BLOCK_REEDS_PLATE);
		registerBlock("reeds_trapdoor", BLOCK_REEDS_TRAPDOOR);
		registerBlock("reeds_door", BLOCK_REEDS_DOOR);
		registerBlockNI("lucis_mushroom", BLOCK_LUCIS_MUSHROOM);
		registerBlock("lucis_spore", BLOCK_LUCIS_SPORE);
		registerBlock("nether_cactus", BLOCK_NETHER_CACTUS);
		registerBlock("wart_seed", BLOCK_WART_SEED);
		registerBlock("barrel_cactus", BLOCK_BARREL_CACTUS);
		registerBlock("agave", BLOCK_AGAVE);
		registerBlock("black_bush", BLOCK_BLACK_BUSH);
		registerBlockNI("ink_bush", BLOCK_INK_BUSH);
		registerBlock("ink_bush_seed", BLOCK_INK_BUSH_SEED);
		registerBlock("smoker", BLOCK_SMOKER);
		registerBlock("egg_plant", BLOCK_EGG_PLANT);
		registerBlockNI("black_apple", BLOCK_BLACK_APPLE);
		registerBlock("black_apple_seed", BLOCK_BLACK_APPLE_SEED);
		registerBlock("magma_flower", BLOCK_MAGMA_FLOWER);
		registerBlock("nether_mycelium", BLOCK_NETHER_MYCELIUM);
		registerBlockNI("red_large_mushroom", BLOCK_RED_LARGE_MUSHROOM);
		registerBlockNI("brown_large_mushroom", BLOCK_BROWN_LARGE_MUSHROOM);
		registerBlock("orange_mushroom", BLOCK_ORANGE_MUSHROOM);
		registerBlock("red_mold", BLOCK_RED_MOLD);
		registerBlock("gray_mold", BLOCK_GRAY_MOLD);
		registerBlock("cincinnasite_ore", BLOCK_CINCINNASITE_ORE);
		registerBlock("cincinnasite_block", BLOCK_CINCINNASITE);
		registerBlock("cincinnasite_forged", BLOCK_CINCINNASITE_FORGED);
		registerBlock("cincinnasite_pillar", BLOCK_CINCINNASITE_PILLAR);
		registerBlock("cincinnasite_bricks", BLOCK_CINCINNASITE_BRICKS);
		registerBlock("cincinnasite_brick_plate", BLOCK_CINCINNASITE_BRICK_PLATE);
		registerBlock("cincinnasite_stairs", BLOCK_CINCINNASITE_STAIRS);
		registerBlock("cincinnasite_slab", BLOCK_CINCINNASITE_SLAB);
		registerBlock("cincinnasite_button", BLOCK_CINCINNASITE_BUTTON);
		registerBlock("cincinnasite_plate", BLOCK_CINCINNASITE_PLATE);
		registerBlock("cincinnasite_lantern", BLOCK_CINCINNASITE_LANTERN);
		registerBlock("cincinnasite_tile_large", BLOCK_CINCINNASITE_TILE_LARGE);
		registerBlock("cincinnasite_tile_small", BLOCK_CINCINNASITE_TILE_SMALL);
		registerBlock("cincinnasite_carved", BLOCK_CINCINNASITE_CARVED);
		registerBlock("nether_brick_tile_large", BLOCK_NETHER_BRICK_TILE_LARGE);
		registerBlock("nether_brick_tile_small", BLOCK_NETHER_BRICK_TILE_SMALL);
		registerBlock("cincinnasite_wall", BLOCK_CINCINNASITE_WALL);
		registerBlock("bone_block", BLOCK_BONE);
		registerBlock("bone_stairs", BLOCK_BONE_STAIRS);
		registerBlock("bone_slab", BLOCK_BONE_SLAB);
		registerBlock("bone_button", BLOCK_BONE_BUTTON);
		registerBlock("bone_plate", BLOCK_BONE_PLATE);
		registerBlock("cincinnasite_fire_bowl", BLOCK_CINCINNASITE_FIRE_BOWL);
		registerBlock("bone_wall", BLOCK_BONE_WALL);
		registerBlock("nether_brick_wall", BLOCK_NETHER_BRICK_WALL);
		registerBlock("nether_brick_tile_slab", BLOCK_NETHER_BRICK_TILE_SLAB);
		registerBlock("nether_brick_tile_stairs", BLOCK_NETHER_BRICK_TILE_STAIRS);
		registerBlock("bone_mushroom", BLOCK_BONE_MUSHROOM);
		registerBlock("reeds_ladder", BLOCK_REEDS_LADDER);
		registerBlock("cincinnasite_bricks_pillar", BLOCK_CINCINNASITE_BRICKS_PILLAR);
		registerBlock("bone_tile", BLOCK_BONE_TILE);
		registerBlock("cincinnasite_pedestal", BLOCK_CINCINNASITE_PEDESTAL);
		registerBlock("pig_statue_respawner", BLOCK_PIG_STATUE_RESPAWNER);
		registerBlock("cincinnasite_pot", BLOCK_CINCINNASITE_POT);
		registerBlockNI("potted_plant", BLOCK_POTTED_PLANT);
		registerBlock("cincinnasite_frame", BLOCK_CINCINNASITE_FRAME);
		registerBlock("quartz_glass", BLOCK_QUARTZ_GLASS);
		registerBlock("quartz_glass_framed", BLOCK_QUARTZ_GLASS_FRAMED);
		registerBlock("quartz_glass_white", BLOCK_QUARTZ_WHITE_GLASS);
		registerBlock("quartz_glass_orange", BLOCK_QUARTZ_ORANGE_GLASS);
		registerBlock("quartz_glass_magenta", BLOCK_QUARTZ_MAGENTA_GLASS);
		registerBlock("quartz_glass_light_blue", BLOCK_QUARTZ_LIGHT_BLUE_GLASS);
		registerBlock("quartz_glass_yellow", BLOCK_QUARTZ_YELLOW_GLASS);
		registerBlock("quartz_glass_lime", BLOCK_QUARTZ_LIME_GLASS);
		registerBlock("quartz_glass_pink", BLOCK_QUARTZ_PINK_GLASS);
		registerBlock("quartz_glass_gray", BLOCK_QUARTZ_GRAY_GLASS);
		registerBlock("quartz_glass_light_gray", BLOCK_QUARTZ_LIGHT_GRAY_GLASS);
		registerBlock("quartz_glass_cyan", BLOCK_QUARTZ_CYAN_GLASS);
		registerBlock("quartz_glass_purple", BLOCK_QUARTZ_PURPLE_GLASS);
		registerBlock("quartz_glass_blue", BLOCK_QUARTZ_BLUE_GLASS);
		registerBlock("quartz_glass_brown", BLOCK_QUARTZ_BROWN_GLASS);
		registerBlock("quartz_glass_green", BLOCK_QUARTZ_GREEN_GLASS);
		registerBlock("quartz_glass_red", BLOCK_QUARTZ_RED_GLASS);
		registerBlock("quartz_glass_black", BLOCK_QUARTZ_BLACK_GLASS);
		registerBlock("cincinnasite_bars", BLOCK_CINCINNASITE_BARS);
		registerBlock("quartz_glass_pane", BLOCK_QUARTZ_GLASS_PANE);
		registerBlock("quartz_glass_framed_pane", BLOCK_QUARTZ_GLASS_FRAMED_PANE);
		registerBlock("cincinnasite_forge", BLOCK_CINCINNASITE_FORGE);
		registerBlock("netherrack_furnace", BLOCK_NETHERRACK_FURNACE);
		registerBlock("bone_reed_door", BLOCK_BONE_REED_DOOR);
		registerBlock("bone_cincinnasite_door", BLOCK_BONE_CINCINNASITE_DOOR);
		registerBlock("quartz_glass_framed_white", BLOCK_QUARTZ_GLASS_FRAMED_WHITE);
		registerBlock("quartz_glass_framed_orange", BLOCK_QUARTZ_GLASS_FRAMED_ORANGE);
		registerBlock("quartz_glass_framed_magenta", BLOCK_QUARTZ_GLASS_FRAMED_MAGENTA);
		registerBlock("quartz_glass_framed_light_blue", BLOCK_QUARTZ_GLASS_FRAMED_LIGHT_BLUE);
		registerBlock("quartz_glass_framed_yellow", BLOCK_QUARTZ_GLASS_FRAMED_YELLOW);
		registerBlock("quartz_glass_framed_lime", BLOCK_QUARTZ_GLASS_FRAMED_LIME);
		registerBlock("quartz_glass_framed_pink", BLOCK_QUARTZ_GLASS_FRAMED_PINK);
		registerBlock("quartz_glass_framed_gray", BLOCK_QUARTZ_GLASS_FRAMED_GRAY);
		registerBlock("quartz_glass_framed_light_gray", BLOCK_QUARTZ_GLASS_FRAMED_LIGHT_GRAY);
		registerBlock("quartz_glass_framed_cyan", BLOCK_QUARTZ_GLASS_FRAMED_CYAN);
		registerBlock("quartz_glass_framed_purple", BLOCK_QUARTZ_GLASS_FRAMED_PURPLE);
		registerBlock("quartz_glass_framed_blue", BLOCK_QUARTZ_GLASS_FRAMED_BLUE);
		registerBlock("quartz_glass_framed_brown", BLOCK_QUARTZ_GLASS_FRAMED_BROWN);
		registerBlock("quartz_glass_framed_green", BLOCK_QUARTZ_GLASS_FRAMED_GREEN);
		registerBlock("quartz_glass_framed_red", BLOCK_QUARTZ_GLASS_FRAMED_RED);
		registerBlock("quartz_glass_framed_black", BLOCK_QUARTZ_GLASS_FRAMED_BLACK);
		registerBlockNI("stalagnate_bowl", BLOCK_STALAGNATE_BOWL);
		registerBlock("chest_of_drawers", BLOCK_CHEST_OF_DRAWERS);
		registerBlock("farmland", FARMLAND);
		registerBlockNI("willow_branch", WILLOW_BRANCH);
		registerBlockNI("willow_leaves", WILLOW_LEAVES);
		registerBlockNI("willow_trunk", WILLOW_TRUNK);
		registerBlock("willow_log", WILLOW_LOG);
		registerBlock("willow_bark", WILLOW_BARK);
		registerBlock("willow_sapling", WILLOW_SAPLING);
		registerBlock("swamp_grass", SWAMP_GRASS);
		registerBlock("willow_planks", WILLOW_PLANKS);
		registerBlock("willow_stairs", BLOCK_WILLOW_STAIRS);
		registerBlock("willow_slab", BLOCK_WILLOW_SLAB);
		registerBlock("willow_fence", BLOCK_WILLOW_FENCE);
		registerBlock("willow_gate", BLOCK_WILLOW_GATE);
		registerBlock("willow_button", BLOCK_WILLOW_BUTTON);
		registerBlock("willow_plate", BLOCK_WILLOW_PLATE);
		registerBlock("willow_trapdoor", BLOCK_WILLOW_TRAPDOOR);
		registerBlock("willow_door", BLOCK_WILLOW_DOOR);
		registerBlock("wart_planks", WART_PLANKS);
		registerBlock("wart_stairs", BLOCK_WART_STAIRS);
		registerBlock("wart_slab", BLOCK_WART_SLAB);
		registerBlock("wart_fence", BLOCK_WART_FENCE);
		registerBlock("wart_gate", BLOCK_WART_GATE);
		registerBlock("wart_button", BLOCK_WART_BUTTON);
		registerBlock("wart_plate", BLOCK_WART_PLATE);
		registerBlock("wart_trapdoor", BLOCK_WART_TRAPDOOR);
		registerBlock("wart_door", BLOCK_WART_DOOR);
		registerBlock("black_vine", BLOCK_BLACK_VINE);
		registerBlockNI("veined_sand", BLOCK_VEINED_SAND);
		registerBlock("soul_vein", BLOCK_SOUL_VEIN);
		registerBlock("blooming_vine", BLOCK_BLOOMING_VINE);
		registerBlock("golden_vine", BLOCK_GOLDEN_VINE);
		registerBlock("geyser", BLOCK_GEYSER);
		registerBlock("mushroom_stem", MUSHROOM_STEM);
		registerBlock("mushroom_planks", MUSHROOM_PLANKS);
		registerBlock("mushroom_stairs", MUSHROOM_STAIRS);
		registerBlock("mushroom_slab", MUSHROOM_SLAB);
		registerBlock("mushroom_fence", MUSHROOM_FENCE);
		registerBlock("mushroom_gate", MUSHROOM_GATE);
		registerBlock("mushroom_button", MUSHROOM_BUTTON);
		registerBlock("mushroom_plate", MUSHROOM_PLATE);
		registerBlock("mushroom_trapdoor", MUSHROOM_TRAPDOOR);
		registerBlock("mushroom_door", MUSHROOM_DOOR);
		registerBlock("cincinnasite_lantern_small", CINCINNASITE_LANTERN_SMALL);
		registerBlock("quartz_glass_pane_white", BLOCK_QUARTZ_GLASS_PANE_WHITE);
		registerBlock("quartz_glass_pane_orange", BLOCK_QUARTZ_GLASS_PANE_ORANGE);
		registerBlock("quartz_glass_pane_magenta", BLOCK_QUARTZ_GLASS_PANE_MAGENTA);
		registerBlock("quartz_glass_pane_light_blue", BLOCK_QUARTZ_GLASS_PANE_LIGHT_BLUE);
		registerBlock("quartz_glass_pane_yellow", BLOCK_QUARTZ_GLASS_PANE_YELLOW);
		registerBlock("quartz_glass_pane_lime", BLOCK_QUARTZ_GLASS_PANE_LIME);
		registerBlock("quartz_glass_pane_pink", BLOCK_QUARTZ_GLASS_PANE_PINK);
		registerBlock("quartz_glass_pane_gray", BLOCK_QUARTZ_GLASS_PANE_GRAY);
		registerBlock("quartz_glass_pane_light_gray", BLOCK_QUARTZ_GLASS_PANE_LIGHT_GRAY);
		registerBlock("quartz_glass_pane_cyan", BLOCK_QUARTZ_GLASS_PANE_CYAN);
		registerBlock("quartz_glass_pane_purple", BLOCK_QUARTZ_GLASS_PANE_PURPLE);
		registerBlock("quartz_glass_pane_blue", BLOCK_QUARTZ_GLASS_PANE_BLUE);
		registerBlock("quartz_glass_pane_brown", BLOCK_QUARTZ_GLASS_PANE_BROWN);
		registerBlock("quartz_glass_pane_green", BLOCK_QUARTZ_GLASS_PANE_GREEN);
		registerBlock("quartz_glass_pane_red", BLOCK_QUARTZ_GLASS_PANE_RED);
		registerBlock("quartz_glass_pane_black", BLOCK_QUARTZ_GLASS_PANE_BLACK);
		registerBlock("quartz_glass_framed_pane_white", BLOCK_QUARTZ_GLASS_FRAMED_PANE_WHITE);
		registerBlock("quartz_glass_framed_pane_orange", BLOCK_QUARTZ_GLASS_FRAMED_PANE_ORANGE);
		registerBlock("quartz_glass_framed_pane_magenta", BLOCK_QUARTZ_GLASS_FRAMED_PANE_MAGENTA);
		registerBlock("quartz_glass_framed_pane_light_blue", BLOCK_QUARTZ_GLASS_FRAMED_PANE_LIGHT_BLUE);
		registerBlock("quartz_glass_framed_pane_yellow", BLOCK_QUARTZ_GLASS_FRAMED_PANE_YELLOW);
		registerBlock("quartz_glass_framed_pane_lime", BLOCK_QUARTZ_GLASS_FRAMED_PANE_LIME);
		registerBlock("quartz_glass_framed_pane_pink", BLOCK_QUARTZ_GLASS_FRAMED_PANE_PINK);
		registerBlock("quartz_glass_framed_pane_gray", BLOCK_QUARTZ_GLASS_FRAMED_PANE_GRAY);
		registerBlock("quartz_glass_framed_pane_light_gray", BLOCK_QUARTZ_GLASS_FRAMED_PANE_LIGHT_GRAY);
		registerBlock("quartz_glass_framed_pane_cyan", BLOCK_QUARTZ_GLASS_FRAMED_PANE_CYAN);
		registerBlock("quartz_glass_framed_pane_purple", BLOCK_QUARTZ_GLASS_FRAMED_PANE_PURPLE);
		registerBlock("quartz_glass_framed_pane_blue", BLOCK_QUARTZ_GLASS_FRAMED_PANE_BLUE);
		registerBlock("quartz_glass_framed_pane_brown", BLOCK_QUARTZ_GLASS_FRAMED_PANE_BROWN);
		registerBlock("quartz_glass_framed_pane_green", BLOCK_QUARTZ_GLASS_FRAMED_PANE_GREEN);
		registerBlock("quartz_glass_framed_pane_red", BLOCK_QUARTZ_GLASS_FRAMED_PANE_RED);
		registerBlock("quartz_glass_framed_pane_black", BLOCK_QUARTZ_GLASS_FRAMED_PANE_BLACK);
		registerBlockNI("soul_lily", BLOCK_SOUL_LILY);
		registerBlock("soul_lily_sapling", BLOCK_SOUL_LILY_SAPLING);
	}
	
	private static void registerBlock(String name, Block block)
	{
		if (Config.getBoolean("blocks", name, true))
		{
			Registry.register(Registry.BLOCK, new Identifier(BetterNether.MOD_ID, name), block);
			ItemsRegister.RegisterItem(name, new BlockItem(block, new Item.Settings().group(CreativeTab.BN_TAB)));
		}
	}
	
	private static void registerBlockNI(String name, Block block)
	{
		if (Config.getBoolean("blocks", name, true))
		{
			Registry.register(Registry.BLOCK, new Identifier(BetterNether.MOD_ID, name), block);
		}
	}
}
